export const brandColors = {
  navy: '#071A3D',
  royal: '#1565D8',
  brand: '#2F80ED',
  white: '#FFFFFF',
  surface: '#F5F8FE',
  ink: '#172033',
  muted: '#64748B',
  border: '#E2E8F0',
} as const;

export const productThemes = {
  corporate: {
    name: 'IHLink Co. Ltd.',
    primary: '#1565D8',
    accent: '#2F80ED',
    bg: '#F5F8FE',
    text: '#071A3D',
    gradient: 'from-royal-500 to-brand-500',
    softBg: '#EAF1FC',
  glow: 'shadow-glow-brand',
  textClass: 'text-royal-600',
    badgeClass: 'bg-royal-50 text-royal-700',
    btnClass: 'bg-royal-500 hover:bg-royal-600',
  ringClass: 'ring-royal-500/20',
  gradClass: 'gradient-text',
  dotPattern: 'dot-pattern',
    gridPattern: 'grid-pattern',
  iconBg: 'bg-brand-50',
    iconText: 'text-brand-600',
  chartColors: ['#1565D8', '#2F80ED', '#73B4F4', '#A8D0F9'],
  heroGradient: 'from-navy-800 via-royal-700 to-brand-500',
  heroPattern: 'grid-pattern',
  badgeText: 'text-brand-700',
    badgeBg: 'bg-brand-50',
    badgeBorder: 'border-brand-200',
    sectionGradient: 'from-surface to-white',
    cardBorder: 'border-border',
    footerBg: 'bg-navy-800',
    footerText: 'text-navy-100',
  announcementBg: 'bg-navy-800',
    announcementText: 'text-white',
  accentBar: 'bg-brand-500',
    statIcon: 'text-brand-600',
    statBg: 'bg-brand-50',
  serviceIcon: 'text-brand-600',
    serviceBg: 'bg-brand-50',
    ctaGradient: 'from-royal-600 to-brand-500',
    linkHover: 'hover:text-brand-600',
    navActive: 'text-brand-600',
    inputFocus: 'focus:ring-brand-500/20 focus:border-brand-500',
    progressBg: 'bg-brand-500',
    switchActive: 'bg-brand-500',
    tabActive: 'border-brand-500 text-brand-600',
    stepperActive: 'bg-brand-500 border-brand-500',
    stepperDone: 'bg-brand-50 text-brand-600 border-brand-200',
    stepperPending: 'bg-gray-100 text-gray-400 border-gray-200',
    chartPrimary: '#1565D8',
    chartSecondary: '#2F80ED',
    chartTertiary: '#73B4F4',
    shadow: 'shadow-card',
    hoverShadow: 'hover:shadow-float',
    ring: 'ring-brand-500/20',
    softSection: 'bg-surface',
    divider: 'border-border',
  },
  datasub: {
    name: 'IHLink DataSub',
    primary: '#10B981',
    accent: '#0EA5E9',
    bg: '#F0FDF4',
    text: '#062A2A',
    gradient: 'from-emerald-500 to-sky-500',
    softBg: '#ECFDF5',
    glow: 'shadow-glow-emerald',
    textClass: 'text-emerald-600',
    badgeClass: 'bg-emerald-50 text-emerald-700',
    btnClass: 'bg-emerald-500 hover:bg-emerald-600',
    ringClass: 'ring-emerald-500/20',
    gradClass: 'gradient-text-emerald',
    dotPattern: 'dot-pattern',
    gridPattern: 'grid-pattern',
    iconBg: 'bg-emerald-50',
    iconText: 'text-emerald-600',
    chartColors: ['#10B981', '#22C55E', '#0EA5E9', '#67E8F9'],
    heroGradient: 'from-emerald-700 via-emerald-600 to-sky-500',
    heroPattern: 'grid-pattern',
    badgeText: 'text-emerald-700',
    badgeBg: 'bg-emerald-50',
    badgeBorder: 'border-emerald-200',
    sectionGradient: 'from-emerald-50/50 to-white',
    cardBorder: 'border-emerald-100',
    footerBg: 'bg-emerald-900',
    footerText: 'text-emerald-100',
    announcementBg: 'bg-emerald-900',
    announcementText: 'text-white',
    accentBar: 'bg-emerald-500',
    statIcon: 'text-emerald-600',
    statBg: 'bg-emerald-50',
    serviceIcon: 'text-emerald-600',
    serviceBg: 'bg-emerald-50',
    ctaGradient: 'from-emerald-600 to-sky-500',
    linkHover: 'hover:text-emerald-600',
    navActive: 'text-emerald-600',
    inputFocus: 'focus:ring-emerald-500/20 focus:border-emerald-500',
    progressBg: 'bg-emerald-500',
    switchActive: 'bg-emerald-500',
    tabActive: 'border-emerald-500 text-emerald-600',
    stepperActive: 'bg-emerald-500 border-emerald-500',
    stepperDone: 'bg-emerald-50 text-emerald-600 border-emerald-200',
    stepperPending: 'bg-gray-100 text-gray-400 border-gray-200',
    chartPrimary: '#10B981',
    chartSecondary: '#22C55E',
    chartTertiary: '#0EA5E9',
    shadow: 'shadow-card',
    hoverShadow: 'hover:shadow-float',
    ring: 'ring-emerald-500/20',
    softSection: 'bg-emerald-50/30',
    divider: 'border-emerald-100',
  },
  schoolpro: {
    name: 'IHLink SchoolPro',
    primary: '#7C3AED',
    accent: '#4F46E5',
    bg: '#F5F3FF',
    text: '#2E1065',
    gradient: 'from-purple-600 to-indigo-600',
    softBg: '#F5F3FF',
    glow: 'shadow-glow-purple',
    textClass: 'text-purple-600',
    badgeClass: 'bg-purple-50 text-purple-700',
    btnClass: 'bg-purple-600 hover:bg-purple-700',
    ringClass: 'ring-purple-500/20',
    gradClass: 'gradient-text-purple',
    dotPattern: 'dot-pattern',
    gridPattern: 'grid-pattern',
    iconBg: 'bg-purple-50',
    iconText: 'text-purple-600',
    chartColors: ['#7C3AED', '#4F46E5', '#FBBF24', '#C4B5FD'],
    heroGradient: 'from-purple-700 via-indigo-600 to-purple-500',
    heroPattern: 'grid-pattern',
    badgeText: 'text-purple-700',
    badgeBg: 'bg-purple-50',
    badgeBorder: 'border-purple-200',
    sectionGradient: 'from-purple-50/50 to-white',
    cardBorder: 'border-purple-100',
    footerBg: 'bg-purple-900',
    footerText: 'text-purple-100',
    announcementBg: 'bg-purple-900',
    announcementText: 'text-white',
    accentBar: 'bg-purple-500',
    statIcon: 'text-purple-600',
    statBg: 'bg-purple-50',
    serviceIcon: 'text-purple-600',
    serviceBg: 'bg-purple-50',
    ctaGradient: 'from-purple-600 to-indigo-600',
    linkHover: 'hover:text-purple-600',
    navActive: 'text-purple-600',
    inputFocus: 'focus:ring-purple-500/20 focus:border-purple-500',
    progressBg: 'bg-purple-500',
    switchActive: 'bg-purple-500',
    tabActive: 'border-purple-500 text-purple-600',
    stepperActive: 'bg-purple-500 border-purple-500',
    stepperDone: 'bg-purple-50 text-purple-600 border-purple-200',
    stepperPending: 'bg-gray-100 text-gray-400 border-gray-200',
    chartPrimary: '#7C3AED',
    chartSecondary: '#4F46E5',
    chartTertiary: '#FBBF24',
    shadow: 'shadow-card',
    hoverShadow: 'hover:shadow-float',
    ring: 'ring-purple-500/20',
    softSection: 'bg-purple-50/30',
    divider: 'border-purple-100',
  },
  consult: {
    name: 'IHLink Consult',
    primary: '#F97316',
    accent: '#DB2777',
    bg: '#FFF7ED',
    text: '#111827',
    gradient: 'from-orange-500 to-pink-600',
    softBg: '#FFF7ED',
    glow: 'shadow-glow-orange',
    textClass: 'text-orange-600',
    badgeClass: 'bg-orange-50 text-orange-700',
    btnClass: 'bg-orange-500 hover:bg-orange-600',
    ringClass: 'ring-orange-500/20',
    gradClass: 'gradient-text-orange',
    dotPattern: 'dot-pattern',
    gridPattern: 'grid-pattern',
    iconBg: 'bg-orange-50',
    iconText: 'text-orange-600',
    chartColors: ['#F97316', '#DB2777', '#7C3AED', '#FDBA74'],
    heroGradient: 'from-orange-700 via-orange-600 to-pink-600',
    heroPattern: 'grid-pattern',
    badgeText: 'text-orange-700',
    badgeBg: 'bg-orange-50',
    badgeBorder: 'border-orange-200',
    sectionGradient: 'from-orange-50/50 to-white',
    cardBorder: 'border-orange-100',
    footerBg: 'bg-gray-900',
    footerText: 'text-gray-300',
    announcementBg: 'bg-gray-900',
    announcementText: 'text-white',
    accentBar: 'bg-orange-500',
    statIcon: 'text-orange-600',
    statBg: 'bg-orange-50',
    serviceIcon: 'text-orange-600',
    serviceBg: 'bg-orange-50',
    ctaGradient: 'from-orange-600 to-pink-600',
    linkHover: 'hover:text-orange-600',
    navActive: 'text-orange-600',
    inputFocus: 'focus:ring-orange-500/20 focus:border-orange-500',
    progressBg: 'bg-orange-500',
    switchActive: 'bg-orange-500',
    tabActive: 'border-orange-500 text-orange-600',
    stepperActive: 'bg-orange-500 border-orange-500',
    stepperDone: 'bg-orange-50 text-orange-600 border-orange-200',
    stepperPending: 'bg-gray-100 text-gray-400 border-gray-200',
    chartPrimary: '#F97316',
    chartSecondary: '#DB2777',
    chartTertiary: '#7C3AED',
    shadow: 'shadow-card',
    hoverShadow: 'hover:shadow-float',
    ring: 'ring-orange-500/20',
    softSection: 'bg-orange-50/30',
    divider: 'border-orange-100',
  },
  host: {
    name: 'IHLink Host', primary: '#0891B2', accent: '#2563EB', bg: '#ECFEFF', text: '#083344',
    gradient: 'from-cyan-600 to-blue-600', softBg: '#ECFEFF', glow: 'shadow-glow-brand',
    textClass: 'text-cyan-700', badgeClass: 'bg-cyan-50 text-cyan-700', btnClass: 'bg-cyan-600 hover:bg-cyan-700',
    ringClass: 'ring-cyan-500/20', gradClass: 'gradient-text', dotPattern: 'dot-pattern', gridPattern: 'grid-pattern',
    iconBg: 'bg-cyan-50', iconText: 'text-cyan-700', chartColors: ['#0891B2','#2563EB','#06B6D4','#60A5FA'],
    heroGradient: 'from-cyan-800 via-cyan-700 to-blue-600', heroPattern: 'grid-pattern', badgeText: 'text-cyan-700',
    badgeBg: 'bg-cyan-50', badgeBorder: 'border-cyan-200', sectionGradient: 'from-cyan-50/60 to-white',
    cardBorder: 'border-cyan-100', footerBg: 'bg-cyan-950', footerText: 'text-cyan-100',
    announcementBg: 'bg-cyan-950', announcementText: 'text-white', accentBar: 'bg-cyan-500', statIcon: 'text-cyan-700',
    statBg: 'bg-cyan-50', serviceIcon: 'text-cyan-700', serviceBg: 'bg-cyan-50', ctaGradient: 'from-cyan-600 to-blue-600',
    linkHover: 'hover:text-cyan-700', navActive: 'text-cyan-700', inputFocus: 'focus:ring-cyan-500/20 focus:border-cyan-500',
    progressBg: 'bg-cyan-500', switchActive: 'bg-cyan-500', tabActive: 'border-cyan-500 text-cyan-700',
    stepperActive: 'bg-cyan-500 border-cyan-500', stepperDone: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    stepperPending: 'bg-gray-100 text-gray-400 border-gray-200', chartPrimary: '#0891B2', chartSecondary: '#2563EB',
    chartTertiary: '#06B6D4', shadow: 'shadow-card', hoverShadow: 'hover:shadow-float', ring: 'ring-cyan-500/20',
    softSection: 'bg-cyan-50/30', divider: 'border-cyan-100',
  },
  engineering: {
    name: 'IHLink Engineering', primary: '#F59E0B', accent: '#D97706', bg: '#FFFBEB', text: '#422006',
    gradient: 'from-amber-500 to-orange-600', softBg: '#FFFBEB', glow: 'shadow-glow-orange', textClass: 'text-amber-700',
    badgeClass: 'bg-amber-50 text-amber-800', btnClass: 'bg-amber-500 hover:bg-amber-600', ringClass: 'ring-amber-500/20',
    gradClass: 'gradient-text-orange', dotPattern: 'dot-pattern', gridPattern: 'grid-pattern', iconBg: 'bg-amber-50', iconText: 'text-amber-700',
    chartColors: ['#F59E0B','#D97706','#F97316','#FCD34D'], heroGradient: 'from-amber-900 via-amber-700 to-orange-600', heroPattern: 'grid-pattern',
    badgeText: 'text-amber-800', badgeBg: 'bg-amber-50', badgeBorder: 'border-amber-200', sectionGradient: 'from-amber-50/60 to-white',
    cardBorder: 'border-amber-100', footerBg: 'bg-amber-950', footerText: 'text-amber-100', announcementBg: 'bg-amber-950', announcementText: 'text-white',
    accentBar: 'bg-amber-500', statIcon: 'text-amber-700', statBg: 'bg-amber-50', serviceIcon: 'text-amber-700', serviceBg: 'bg-amber-50',
    ctaGradient: 'from-amber-500 to-orange-600', linkHover: 'hover:text-amber-700', navActive: 'text-amber-700', inputFocus: 'focus:ring-amber-500/20 focus:border-amber-500',
    progressBg: 'bg-amber-500', switchActive: 'bg-amber-500', tabActive: 'border-amber-500 text-amber-700', stepperActive: 'bg-amber-500 border-amber-500',
    stepperDone: 'bg-amber-50 text-amber-700 border-amber-200', stepperPending: 'bg-gray-100 text-gray-400 border-gray-200', chartPrimary: '#F59E0B',
    chartSecondary: '#D97706', chartTertiary: '#F97316', shadow: 'shadow-card', hoverShadow: 'hover:shadow-float', ring: 'ring-amber-500/20',
    softSection: 'bg-amber-50/30', divider: 'border-amber-100',
  },
} as const;

export type ProductKey = keyof typeof productThemes;

export const naira = (amount: number): string => {
  return '₦' + amount.toLocaleString('en-NG', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
};

export const formatDate = (dateStr: string): string => {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' });
};

export const formatDateTime = (dateStr: string): string => {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' }) +
    ' · ' + d.toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit' });
};

export const statusBadgeClass = (status: string): string => {
  const map: Record<string, string> = {
    success: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    completed: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    active: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    approved: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    paid: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    pending: 'bg-amber-50 text-amber-700 border-amber-200',
    processing: 'bg-amber-50 text-amber-700 border-amber-200',
    reviewing: 'bg-amber-50 text-amber-700 border-amber-200',
    draft: 'bg-gray-100 text-gray-600 border-gray-200',
    failed: 'bg-rose-50 text-rose-700 border-rose-200',
    rejected: 'bg-rose-50 text-rose-700 border-rose-200',
    cancelled: 'bg-rose-50 text-rose-700 border-rose-200',
    overdue: 'bg-rose-50 text-rose-700 border-rose-200',
    inactive: 'bg-gray-100 text-gray-500 border-gray-200',
    locked: 'bg-rose-50 text-rose-700 border-rose-200',
    published: 'bg-blue-50 text-blue-700 border-blue-200',
    sent: 'bg-blue-50 text-blue-700 border-blue-200',
    open: 'bg-blue-50 text-blue-700 border-blue-200',
    in_progress: 'bg-amber-50 text-amber-700 border-amber-200',
    on_track: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    at_risk: 'bg-amber-50 text-amber-700 border-amber-200',
    delayed: 'bg-rose-50 text-rose-700 border-rose-200',
  };
  return map[status.toLowerCase()] || 'bg-gray-100 text-gray-600 border-gray-200';
};

export const statusLabel = (status: string): string => {
  const map: Record<string, string> = {
    success: 'Success',
    completed: 'Completed',
    active: 'Active',
    approved: 'Approved',
    paid: 'Paid',
    pending: 'Pending',
    processing: 'Processing',
    reviewing: 'Under Review',
    draft: 'Draft',
    failed: 'Failed',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    overdue: 'Overdue',
    inactive: 'Inactive',
    locked: 'Locked',
    published: 'Published',
    sent: 'Sent',
    open: 'Open',
    in_progress: 'In Progress',
    on_track: 'On Track',
    at_risk: 'At Risk',
    delayed: 'Delayed',
  };
  return map[status.toLowerCase()] || status;
};
