export interface RouteEntry {
  path: string;
  name: string;
  product: string;
  role: string;
  status: 'designed' | 'placeholder';
}

export interface RouteGroup { title: string; icon: string; routes: RouteEntry[] }

export const routeGroups: RouteGroup[] = [
  {
    title: "IHLink Corporate",
    icon: "Building2",
    routes: [
      { path: "/", name: "Homepage", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/about", name: "About", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/services", name: "Services Directory", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/onboarding", name: "Onboarding Wizard", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/contact", name: "Contact", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/portfolio", name: "Portfolio", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/case-studies", name: "Case Studies", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/testimonials", name: "Testimonials", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/blog", name: "Blog Listing", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/blog/article", name: "Blog Article", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/careers", name: "Careers", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/partners", name: "Partners", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/faq", name: "FAQ", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/privacy", name: "Privacy Policy", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/terms", name: "Terms & Conditions", product: "Corporate", role: "Public", status: 'designed' },
      { path: "/support", name: "Support", product: "Corporate", role: "Public", status: 'designed' },
    ],
  },
  {
    title: "IHLink DataSub",
    icon: "Smartphone",
    routes: [
      { path: "/datasub", name: "Homepage", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/airtime", name: "Airtime", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/data-plans", name: "Data Plans", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/electricity", name: "Electricity", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/cable", name: "Cable TV", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/education", name: "Education Services", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/reseller", name: "Reseller Page", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/api", name: "Developer API", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/pricing", name: "Pricing", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/faq", name: "FAQ", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/support", name: "Support", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/dashboard", name: "DataSub Dashboard", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/wallet", name: "Wallet", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/transactions", name: "Transactions", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/buy-airtime", name: "Buy Airtime", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/buy-data", name: "Buy Data", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/pay-electricity", name: "Pay Electricity", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/pay-cable", name: "Pay Cable", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/buy-education", name: "Buy Education PIN", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/reseller-dashboard", name: "Reseller Dashboard", product: "DataSub", role: "Customer", status: 'designed' },
      { path: "/datasub/api-dashboard", name: "API Dashboard", product: "DataSub", role: "Customer", status: 'designed' },
    ],
  },
  {
    title: "IHLink SchoolPro",
    icon: "GraduationCap",
    routes: [
      { path: "/schoolpro", name: "Homepage", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/features", name: "Features", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/result-management", name: "Result Management", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/pricing", name: "Pricing", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/book-demo", name: "Book Demo", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/register", name: "Register School", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/faq", name: "FAQ", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/support", name: "Support", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/login", name: "School Login", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/parent-login", name: "Parent Login", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/student-login", name: "Student Login", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/teacher-login", name: "Teacher Login", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/result-checker", name: "Result Checker", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/proprietor-dashboard", name: "Proprietor Dashboard", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/admin-dashboard", name: "Admin Dashboard", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/students", name: "Students", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/results", name: "Results", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/fees", name: "Fees & Finance", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/report-card", name: "Report Card", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/teacher-dashboard", name: "Teacher Dashboard", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/parent-dashboard", name: "Parent Dashboard", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/student-dashboard", name: "Student Dashboard", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/admissions", name: "Admissions", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/staff", name: "Staff", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/parents", name: "Parents", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/classes", name: "Classes", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/subjects", name: "Subjects", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/attendance", name: "Attendance", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/timetable", name: "Timetable", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/assignments", name: "Assignments", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/cbt", name: "Cbt", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/library", name: "Library", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/transport", name: "Transport", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/hostel", name: "Hostel", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/inventory", name: "Inventory", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/payroll", name: "Payroll", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/medical", name: "Medical", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/discipline", name: "Discipline", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/announcements", name: "Announcements", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/reports", name: "Reports", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/settings", name: "Settings", product: "SchoolPro", role: "School User", status: 'designed' },
      { path: "/schoolpro/roles-permissions", name: "Roles Permissions", product: "SchoolPro", role: "School User", status: 'designed' },
    ],
  },
  {
    title: "IHLink Consult",
    icon: "Wrench",
    routes: [
      { path: "/consult", name: "Homepage", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/services", name: "All Services", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/services/web-mobile", name: "Web & Mobile", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/services/ai-ml", name: "AI & ML", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/services/cloud-devops", name: "Cloud & DevOps", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/services/engineering", name: "Computer Engineering", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/hire", name: "Hire Us", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/portfolio", name: "Portfolio", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/portfolio/case-study", name: "Case Study", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/quote", name: "Request Quote", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/book", name: "Book Consultation", product: "Consult", role: "Client", status: 'designed' },
      { path: "/consult/portal", name: "Client Portal", product: "Consult", role: "Client", status: 'designed' },
    ],
  },
  {
    title: "IHLink Host",
    icon: "Server",
    routes: [
      { path: "/host", name: "Hosting Homepage", product: "Host", role: "Public", status: 'designed' },
      { path: "/host/domains", name: "Domain Search", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/hosting", name: "Web Hosting", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/reseller", name: "Reseller Hosting", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/vps", name: "Cloud VPS", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/dedicated", name: "Dedicated Servers", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/order", name: "Hosting Checkout", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/dashboard", name: "Customer Dashboard", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/dashboard/domains", name: "My Domains", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/dashboard/services", name: "My Services", product: "Host", role: "Customer", status: 'designed' },
      { path: "/host/support", name: "Hosting Support", product: "Host", role: "Customer", status: 'designed' },
    ],
  },
  {
    title: "IHLink Engineering",
    icon: "Cpu",
    routes: [
      { path: "/engineering", name: "Engineering Homepage", product: "Engineering", role: "Public", status: 'designed' },
      { path: "/engineering/control", name: "Control Systems", product: "Engineering", role: "Client", status: 'designed' },
      { path: "/engineering/robotics", name: "Robotics & Automation", product: "Engineering", role: "Client", status: 'designed' },
      { path: "/engineering/instrumentation", name: "Instrumentation", product: "Engineering", role: "Client", status: 'designed' },
      { path: "/engineering/networking", name: "Networking", product: "Engineering", role: "Client", status: 'designed' },
      { path: "/engineering/quote", name: "Request Project", product: "Engineering", role: "Client", status: 'designed' },
      { path: "/engineering/portfolio", name: "Portfolio", product: "Engineering", role: "Public", status: 'designed' },
      { path: "/engineering/dashboard", name: "Client Workspace", product: "Engineering", role: "Client", status: 'designed' },
      { path: "/engineering/support", name: "Engineering Support", product: "Engineering", role: "Client", status: 'designed' },
    ],
  },
  {
    title: "Shared Authentication",
    icon: "Lock",
    routes: [
      { path: "/signin", name: "Sign In", product: "Shared", role: "Public", status: 'designed' },
      { path: "/register", name: "Registration", product: "Shared", role: "Public", status: 'designed' },
      { path: "/reset-password", name: "Password Reset", product: "Shared", role: "Public", status: 'designed' },
      { path: "/verify-email", name: "Email Verification", product: "Shared", role: "Public", status: 'designed' },
      { path: "/welcome-tour", name: "New User Product Tour", product: "Shared", role: "New User", status: 'designed' },
    ],
  },
  {
    title: "Shared Account",
    icon: "User",
    routes: [
      { path: "/account", name: "Central Customer Dashboard", product: "Shared", role: "User", status: 'designed' },
      { path: "/dashboard", name: "Customer Dashboard Redirect", product: "Shared", role: "User", status: 'designed' },
      { path: "/account/notifications", name: "Notification Centre", product: "Shared", role: "User", status: 'designed' },
      { path: "/account/profile", name: "Profile & Security", product: "Shared", role: "User", status: 'designed' },
    ],
  },
  {
    title: "IHLink Central Super Admin",
    icon: "ShieldCheck",
    routes: [
      { path: "/admin/login", name: "Admin Login", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/verify", name: "Two-Factor Verification", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin", name: "Central Overview", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/products", name: "Products", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/administrators", name: "Administrators", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/roles", name: "Roles & Permissions", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/customers", name: "Customers", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/content", name: "Corporate Content", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/datasub", name: "DataSub Administration", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/datasub/transactions", name: "DataSub Transactions", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/schoolpro", name: "SchoolPro Administration", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/schools", name: "Schools", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/subscriptions", name: "Subscriptions", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/consult", name: "Consult Operations", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/host", name: "Domains & Hosting", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/engineering", name: "Engineering Operations", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/leads", name: "Lead Pipeline", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/projects", name: "Projects", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/finance", name: "Finance", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/payments", name: "Payments", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/support", name: "Support", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/notifications", name: "Notifications", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/security", name: "Security Centre", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/readiness", name: "Launch Readiness", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/audit-logs", name: "Audit Logs", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/integrations", name: "Integrations", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/settings", name: "Settings", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/access-denied", name: "Access Denied", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/session-expired", name: "Session Expired", product: "Admin", role: "Administrator", status: 'designed' },
      { path: "/admin/system-error", name: "System Error", product: "Admin", role: "Administrator", status: 'designed' },
    ],
  },
  {
    title: "UI Kit",
    icon: "Palette",
    routes: [
      { path: "/ui-kit", name: "UI Component Library", product: "Shared", role: "Designer", status: 'designed' },
    ],
  },
];
