import {SchoolClassSelect} from '@/components/SchoolClassSelect';
import {customerMessage} from '@/lib/customerMessage';
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarCheck2, RefreshCw, Save, Users } from "lucide-react";
import { ModulePage } from "@/components/ModulePage";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { useSchoolProContext } from "@/hooks/useSchoolProContext";
import { schoolSections, status } from "./schoolShared";

type School={id:string;name:string};type ClassRow={id:string;name:string;arm:string;level?:string|null};type Student={id:string;first_name:string;last_name:string;admission_number:string};type AttendanceStatus="present"|"absent"|"late"|"excused";type AttendanceRow={student_id:string;status:AttendanceStatus;notes:string|null};
const today=new Date().toISOString().slice(0,10);
export function SchoolProAttendance(){
 const {user,profile}=useAuth();const ctx=useSchoolProContext();const [schools,setSchools]=useState<School[]>([]),[schoolId,setSchoolId]=useState(""),[classes,setClasses]=useState<ClassRow[]>([]),[classId,setClassId]=useState(""),[date,setDate]=useState(today),[students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<Record<string,{status:AttendanceStatus;notes:string}>>({}),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);const userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(" ")||profile.email:"School User";
 const loadSchools=useCallback(async()=>{if(!supabase||!user||ctx.loading)return;if(ctx.schoolId){setSchools([{id:ctx.schoolId,name:ctx.schoolName}]);setSchoolId(ctx.schoolId);}else{setSchools([]);setSchoolId("");}},[user,ctx.loading,ctx.schoolId,ctx.schoolName]);
 const loadClasses=useCallback(async()=>{if(!supabase||!schoolId)return;const {data,error}=await supabase.from("schoolpro_classes").select("id,name,arm,level").eq("school_id",schoolId).order("name");if(error)setError(customerMessage(error.message));const next=(data||[]) as ClassRow[];setClasses(next);setClassId(current=>next.some(x=>x.id===current)?current:next[0]?.id||"");},[schoolId]);
 const loadRegister=useCallback(async()=>{if(!supabase||!schoolId||!classId)return;setError(null);const [a,b]=await Promise.all([supabase.from("schoolpro_students").select("id,first_name,last_name,admission_number").eq("school_id",schoolId).eq("class_id",classId).eq("status","active").order("first_name"),supabase.from("schoolpro_attendance").select("student_id,status,notes").eq("school_id",schoolId).eq("class_id",classId).eq("attendance_date",date)]);const issue=a.error||b.error;if(issue){setError(customerMessage(issue.message));return;}const roster=(a.data||[]) as Student[],saved=(b.data||[]) as AttendanceRow[];const map=new Map(saved.map(x=>[x.student_id,x]));setStudents(roster);setRecords(Object.fromEntries(roster.map(student=>{const row=map.get(student.id);return [student.id,{status:row?.status||"present",notes:row?.notes||""}]})));},[schoolId,classId,date]);
 useEffect(()=>{void loadSchools();},[loadSchools]);useEffect(()=>{void loadClasses();},[loadClasses]);useEffect(()=>{void loadRegister();},[loadRegister]);
 async function save(){if(!supabase||!user||!schoolId||!classId||!students.length)return;setBusy(true);setError(null);const rows=students.map(student=>({school_id:schoolId,class_id:classId,student_id:student.id,attendance_date:date,status:records[student.id]?.status||"present",notes:records[student.id]?.notes||null,marked_by:user.id}));const {error}=await supabase.from("schoolpro_attendance").upsert(rows,{onConflict:"student_id,attendance_date"});if(error)setError(customerMessage(error.message));else setMessage(`Attendance saved for ${students.length} students.`);setBusy(false);}
 const counts=useMemo(()=>({present:students.filter(x=>records[x.id]?.status==="present").length,absent:students.filter(x=>records[x.id]?.status==="absent").length,late:students.filter(x=>records[x.id]?.status==="late").length}),[students,records]);
 return <ModulePage product="schoolpro" sections={schoolSections} title="Daily Attendance" description="Open a class register, mark every learner and keep a searchable daily attendance history." userName={userName} userRole="School Educator" primaryAction="Save Register" metrics={[{label:"Class Size",value:String(students.length)},{label:"Present",value:String(counts.present)},{label:"Absent",value:String(counts.absent),tone:"text-rose-600"},{label:"Late",value:String(counts.late),tone:"text-amber-600"}]}>
 {(error||message)&&<div className={`rounded-xl border p-3 text-sm ${error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error||message}</div>}
 <Card><div className="grid gap-3 md:grid-cols-4"><select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="rounded-lg border p-2.5 text-sm">{schools.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><SchoolClassSelect classes={classes} value={classId} onChange={value=>setClassId(value)}/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-lg border p-2.5 text-sm"/><Button variant="secondary" onClick={()=>void loadRegister()} leftIcon={<RefreshCw className="h-4 w-4"/>}>Refresh Register</Button></div></Card>
 <Card padding="none" className="overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div className="flex items-center gap-2"><CalendarCheck2 className="h-5 w-5 text-purple-700"/><h3 className="font-bold">Class register · {date}</h3></div>{status(`${counts.present}/${students.length} present`)}</div><div className="overflow-x-auto"><div className="school-table-scroll"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{["Student","Admission No.","Attendance","Note"].map(x=><th key={x} className="p-3 text-xs uppercase text-muted">{x}</th>)}</tr></thead><tbody>{students.map(student=><tr key={student.id} className="border-t"><td className="p-3 font-bold">{student.first_name} {student.last_name}</td><td className="p-3">{student.admission_number}</td><td className="p-3"><select value={records[student.id]?.status||"present"} onChange={e=>setRecords({...records,[student.id]:{...records[student.id],status:e.target.value as AttendanceStatus,notes:records[student.id]?.notes||""}})} className="rounded-lg border px-2 py-1.5 text-sm"><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></td><td className="p-3"><input value={records[student.id]?.notes||""} onChange={e=>setRecords({...records,[student.id]:{status:records[student.id]?.status||"present",notes:e.target.value}})} placeholder="Optional note" className="w-full min-w-48 rounded-lg border p-2 text-sm"/></td></tr>)}</tbody></table></div>{!students.length&&<div className="p-10 text-center text-sm text-muted"><Users className="mx-auto mb-2 h-8 w-8"/>No active students are assigned to this class.</div>}</div><div className="border-t p-4"><Button onClick={()=>void save()} disabled={busy||!students.length} leftIcon={<Save className="h-4 w-4"/>}>{busy?"Saving…":"Save Attendance"}</Button></div></Card>
 </ModulePage>;
}
