import {SchoolStudentSelect} from '@/components/SchoolStudentSelect';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {useAuth} from '@/context/AuthContext';
import {useSchoolProContext} from '@/hooks/useSchoolProContext';
import {supabase} from '@/lib/supabase';
import {ModulePage} from '@/components/ModulePage';
import {SchoolStudentFilters} from '@/components/SchoolStudentFilters';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {schoolSections} from './schoolShared';
type Student={id:string;first_name:string;last_name:string;class_id:string|null;class_name:string};
type Concern={id:string;student_id:string;incident:string;action_taken:string|null;status:string;created_at:string};
export function SchoolProDiscipline(){
 const ctx=useSchoolProContext(),{user}=useAuth();const leadership=['proprietor','administrator','super administrator','vice principal','head teacher','counsellor'].includes(ctx.role.toLowerCase().replaceAll("_"," "));
 const [students,setStudents]=useState<Student[]>([]),[ids,setIds]=useState<string[]>([]),[rows,setRows]=useState<Concern[]>([]),[student,setStudent]=useState(''),[incident,setIncident]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[actions,setActions]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(!supabase||!ctx.schoolId)return;const[a,b]=await Promise.all([supabase.from('schoolpro_students').select('id,first_name,last_name,class_id,class_name').eq('school_id',ctx.schoolId).eq('status','active'),supabase.from('schoolpro_discipline_records').select('id,student_id,incident,action_taken,status,created_at').eq('school_id',ctx.schoolId).order('created_at',{ascending:false}).limit(200)]);if(a.error||b.error){setMessage('School concerns could not be loaded. Please try again.');return;}setStudents(a.data||[]);setRows(b.data||[]);setActions(Object.fromEntries((b.data||[]).map(r=>[r.id,r.action_taken||''])));},[ctx.schoolId]);
 useEffect(()=>{setStudents([]);setRows([]);void load()},[load]);useEffect(()=>{if(student&&!ids.includes(student))setStudent('')},[ids,student]);
 const names=useMemo(()=>new Map(students.map(s=>[s.id,`${s.first_name} ${s.last_name} · ${s.class_name}`])),[students]);
 async function report(){if(!supabase||!user||!student||!incident.trim()||busy)return;setBusy(true);const{error}=await supabase.from('schoolpro_discipline_records').insert({school_id:ctx.schoolId,student_id:student,incident:incident.trim(),status:'open',created_by:user.id});setBusy(false);if(error)setMessage('The concern could not be saved. Please check your school access and try again.');else{setIncident('');setMessage('Concern submitted. School leadership has been notified.');await load();}}
 async function review(row:Concern,close:boolean){if(!supabase||!leadership||busy)return;setBusy(true);const r=await supabase.from('schoolpro_discipline_records').update({action_taken:actions[row.id]?.trim()||null,status:close?'resolved':'open'}).eq('id',row.id).eq('school_id',ctx.schoolId).select('id').maybeSingle();setBusy(false);setMessage(r.error||!r.data?'The review could not be saved. Please try again.':'School follow-up saved.');if(!r.error&&r.data)await load();}
 return <ModulePage product="schoolpro" sections={schoolSections} title="Student concerns & discipline" description="Report a concern to school leadership and record the school's follow-up." userName={ctx.schoolName} userRole={ctx.role}><Card><SchoolStudentFilters schoolId={ctx.schoolId||''} students={students} onChange={setIds}/><div><SchoolStudentSelect schoolId={ctx.schoolId} students={students} value={student} onChange={setStudent}/></div><label className="mt-3 block text-sm font-semibold">Concern<textarea className="mt-1 w-full rounded-xl border p-3" rows={4} value={incident} onChange={e=>setIncident(e.target.value)} maxLength={4000}/></label><Button className="mt-3" disabled={busy||!student||!incident.trim()} onClick={()=>void report()}>Report concern</Button>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</Card><div className="grid gap-4">{rows.filter(r=>!r.student_id||ids.includes(r.student_id)).map(r=><Card key={r.id}><h3 className="font-bold">{names.get(r.student_id)||'School concern'}</h3><p className="text-xs text-muted">{new Date(r.created_at).toLocaleDateString()} · {r.status}</p><p className="mt-3 whitespace-pre-wrap">{r.incident}</p>{leadership?<><label className="mt-3 block text-sm font-semibold">School follow-up<textarea className="mt-1 w-full rounded-xl border p-3" rows={3} value={actions[r.id]||''} onChange={e=>setActions({...actions,[r.id]:e.target.value})}/></label><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void review(r,false)}>Save follow-up</Button><Button variant="secondary" disabled={busy} onClick={()=>void review(r,true)}>Resolve concern</Button></div></>:r.action_taken&&<p className="mt-3">School follow-up: {r.action_taken}</p>}</Card>)}</div></ModulePage>
}
