import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {customerMessage} from '@/lib/customerMessage';
import {ModulePage} from '@/components/ModulePage';
import {schoolSections} from './schoolShared';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {SchoolClassSelect} from '@/components/SchoolClassSelect';
import {supabase} from '@/lib/supabase';
import {useSchoolProContext} from '@/hooks/useSchoolProContext';
export function SchoolProAdmissionOperations(){
 const ctx=useSchoolProContext();const[applications,setApplications]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[classId,setClassId]=useState(''),[id,setId]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setApplications([]);setClasses([]);setId('');setClassId('');setMsg('');if(supabase&&ctx.schoolId)void Promise.all([supabase.from('schoolpro_admissions').select('id,applicant_name,class_applied,application_number,enrollment_status').eq('school_id',ctx.schoolId).order('created_at',{ascending:false}),supabase.from('schoolpro_classes').select('id,name,arm,level').eq('school_id',ctx.schoolId)]).then(([a,b])=>{if(active){if(a.error||b.error)setMsg('Admissions could not be loaded. Please try again.');else{setApplications(a.data||[]);setClasses(b.data||[])}}});return()=>{active=false}},[ctx.schoolId]);
 const chosen=classes.find(c=>c.id===classId);const available=applications.filter(a=>a.enrollment_status!=='enrolled'&&(!chosen||a.class_applied===chosen.name||a.class_applied===[chosen.name,chosen.arm].filter(Boolean).join(' ')));
 async function enroll(){if(!supabase||!id||busy)return;setBusy(true);try{const r=await supabase.rpc('finalize_schoolpro_enrollment',{p_application:id});if(r.error){setMsg(customerMessage(r.error.message));return;}setApplications(a=>a.map(x=>x.id===id?{...x,enrollment_status:'enrolled'}:x));setId('');setMsg('Enrolment completed. The student is available in your school records.');}catch{setMsg('Enrolment could not be completed. Please try again.');}finally{setBusy(false)}}
 return <ModulePage product="schoolpro" sections={schoolSections} title="Admission Operations" description="Complete accepted admissions and manage access for your school community." userName={ctx.schoolName} userRole={ctx.role}><div className="grid gap-5 md:grid-cols-2"><Card><h2 className="font-bold">Finalize enrolment</h2><p className="mt-2 text-sm">The admission offer and terms must be accepted before enrolment can be completed.</p><SchoolClassSelect classes={classes} value={classId} onChange={value=>{setClassId(value);setId('')}}/><label className="mt-3 block">Applicant<select value={id} onChange={e=>setId(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">Choose applicant</option>{available.map(a=><option key={a.id} value={a.id}>{a.applicant_name} · {a.class_applied} · {a.application_number||'Application'}</option>)}</select></label><Button disabled={busy||!id} className="mt-3" onClick={()=>void enroll()}>{busy?'Completing…':'Finalize enrolment'}</Button></Card><Card><h2 className="font-bold">School account access</h2><p className="mt-3">Add staff accounts or link parents to their children in your school’s access pages.</p><div className="mt-4 flex flex-wrap gap-3"><Link className="font-bold text-blue-600" to="/schoolpro/staff">Staff &amp; access</Link><Link className="font-bold text-blue-600" to="/schoolpro/parents">Parents &amp; guardians</Link><Link className="font-bold text-blue-600" to="/schoolpro/students">Student records</Link></div></Card></div>{msg&&<p role="status" className="mt-4 font-semibold">{msg}</p>}</ModulePage>
}
