import {SchoolClassSelect} from '@/components/SchoolClassSelect';
import {customerMessage} from '@/lib/customerMessage';
import {AcademicPeriodSelect} from '@/components/AcademicPeriodSelect';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { BookOpen, Plus, RefreshCw, Trash2, UserRoundCheck } from "lucide-react";
import { ModulePage } from "@/components/ModulePage";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { schoolSections, status } from "./schoolShared";
import { useSchoolProContext } from "@/hooks/useSchoolProContext";

type School = { id:string; name:string };
type ClassRow = { id:string; name:string; arm:string };
type Subject = { id:string; name:string; code:string; class_name:string };
type Member = { id:string; user_id:string; role:string; name:string };
type Assignment = { id:string; class_id:string; subject_id:string; teacher_member_id:string|null; session:string };

export function SchoolProSubjects(){
  const {user,profile}=useAuth();const ctx=useSchoolProContext();const canManage=['proprietor','administrator','super administrator'].includes(ctx.role.toLowerCase());
  const [schools,setSchools]=useState<School[]>([]),[schoolId,setSchoolId]=useState("");
  const [classes,setClasses]=useState<ClassRow[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[members,setMembers]=useState<Member[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[tableSearch,setTableSearch]=useState("");
  const [form,setForm]=useState({name:"",code:"",className:""});
  const [allocation,setAllocation]=useState({classId:"",subjectId:"",teacherId:"",session:"2026/2027"});
  const [error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(" ")||profile.email:"School User";

  const loadSchools=useCallback(async()=>{if(!supabase||!user)return;const {data,error}=await supabase.from("schoolpro_schools").select("id,name").order("name");if(error)setError(customerMessage(error.message));const next=(data||[]) as School[];setSchools(next);setSchoolId(current=>current||next[0]?.id||"");},[user]);
  const load=useCallback(async()=>{if(!supabase||!schoolId)return;setError(null);const [a,b,c,d]=await Promise.all([
    supabase.from("schoolpro_classes").select("id,name,arm,level").eq("school_id",schoolId).order("name"),
    supabase.from("schoolpro_subjects").select("id,name,code,class_name").eq("school_id",schoolId).order("name"),
    supabase.from("schoolpro_members").select("id,user_id,role").eq("school_id",schoolId).in("role",["teacher","class_teacher","administrator","proprietor"]).match(canManage?{}:{user_id:user?.id}),
    supabase.from("schoolpro_subject_assignments").select("id,class_id,subject_id,teacher_member_id,session").eq("school_id",schoolId).order("created_at")
  ]);const issue=a.error||b.error||c.error||d.error;if(issue){setError(customerMessage(issue.message));return;}const raw=(c.data||[]) as Omit<Member,"name">[];const ids=raw.map(x=>x.user_id);let names=new Map<string,string>();if(ids.length){const p=await supabase.from("profiles").select("id,first_name,last_name,email").in("id",ids);if(p.error){setError(customerMessage(p.error.message));return;}names=new Map((p.data||[]).map(x=>[x.id,[x.first_name,x.last_name].filter(Boolean).join(" ")||x.email]));}setClasses((a.data||[]) as ClassRow[]);setSubjects((b.data||[]) as Subject[]);setMembers(raw.map(x=>({...x,name:names.get(x.user_id)||x.role})));setAssignments((d.data||[]) as Assignment[]);},[schoolId]);
  useEffect(()=>{void loadSchools();},[loadSchools]);useEffect(()=>{void load();},[load]);
  async function addSubject(e:FormEvent){e.preventDefault();if(!supabase||!schoolId||!canManage)return;setMessage(null);const {error}=await supabase.from("schoolpro_subjects").insert({school_id:schoolId,name:form.name,code:form.code.toUpperCase(),class_name:form.className});if(error)setError(customerMessage(error.message));else{setForm({name:"",code:"",className:""});setMessage("Subject created.");await load();}}
  async function assign(e:FormEvent){e.preventDefault();if(!supabase||!schoolId||!canManage)return;const {error}=await supabase.from("schoolpro_subject_assignments").upsert({school_id:schoolId,class_id:allocation.classId,subject_id:allocation.subjectId,teacher_member_id:allocation.teacherId||null,session:allocation.session},{onConflict:"class_id,subject_id,session"});if(error)setError(customerMessage(error.message));else{setMessage("Subject and teacher allocation saved.");await load();}}
  async function remove(id:string){if(!supabase||!canManage||!window.confirm("Remove this allocation?"))return;const {error}=await supabase.from("schoolpro_subject_assignments").delete().eq("id",id);if(error)setError(customerMessage(error.message));else await load();}
  const classMap=useMemo(()=>new Map(classes.map(x=>[x.id,`${x.name}${x.arm?` ${x.arm}`:""}`])),[classes]),subjectMap=useMemo(()=>new Map(subjects.map(x=>[x.id,x.name])),[subjects]),memberMap=useMemo(()=>new Map(members.map(x=>[x.id,x.name])),[members]);
  return <ModulePage product="schoolpro" sections={schoolSections} title={canManage?"Subjects & Teacher Allocation":"My Classes & Subjects"} description="Build the curriculum for each class and assign the responsible teacher for every academic session." userName={userName} userRole={ctx.role} primaryAction="Add Subject" metrics={[{label:"Subjects",value:String(subjects.length)},{label:"Allocations",value:String(assignments.length)},{label:"Teachers",value:String(members.filter(x=>x.role==="teacher").length)},{label:"Unassigned",value:String(assignments.filter(x=>!x.teacher_member_id).length)}]}>
    {(error||message)&&<div className={`rounded-xl border p-3 text-sm ${error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error||message}</div>}
    <div className="flex justify-between gap-3"><select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-sm">{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button variant="secondary" size="sm" onClick={()=>void load()} leftIcon={<RefreshCw className="h-4 w-4"/>}>Refresh</Button></div>
    {canManage&&<div className="grid gap-5 xl:grid-cols-2"><Card><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-purple-700"/><h3 className="font-bold">Create subject</h3></div><form onSubmit={addSubject} className="mt-4 grid gap-3 sm:grid-cols-2"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Subject name" className="rounded-lg border p-2.5 text-sm"/><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Code, e.g. MTH" className="rounded-lg border p-2.5 text-sm"/><input required value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="Curriculum group, e.g. Primary" className="rounded-lg border p-2.5 text-sm sm:col-span-2"/><Button className="sm:col-span-2" leftIcon={<Plus className="h-4 w-4"/>}>Add Subject</Button></form></Card>
    <Card><div className="flex items-center gap-2"><UserRoundCheck className="h-5 w-5 text-purple-700"/><h3 className="font-bold">Allocate class, subject and teacher</h3></div><form onSubmit={assign} className="mt-4 grid gap-3 sm:grid-cols-2"><SchoolClassSelect classes={classes} value={allocation.classId} onChange={value=>setAllocation({...allocation,classId:value})} required/><select required value={allocation.subjectId} onChange={e=>setAllocation({...allocation,subjectId:e.target.value})} className="rounded-lg border p-2.5 text-sm"><option value="">Select subject</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={allocation.teacherId} onChange={e=>setAllocation({...allocation,teacherId:e.target.value})} className="rounded-lg border p-2.5 text-sm"><option value="">Teacher not assigned</option>{members.map(x=><option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select><AcademicPeriodSelect kind="session" required value={allocation.session} onChange={e=>setAllocation({...allocation,session:e.target.value})} className="rounded-lg border p-2.5 text-sm"/><Button className="sm:col-span-2">Save Allocation</Button></form></Card></div>}
    <Card padding="none" className="overflow-hidden"><div className="border-b p-3"><input type="search" aria-label="Search allocations" placeholder="Search class, subject or teacher" value={tableSearch} onChange={e=>setTableSearch(e.target.value)} className="w-full max-w-sm rounded-lg border p-2 text-sm"/></div><div className="max-h-[70vh] overflow-auto"><div className="school-table-scroll"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{["Class","Subject","Teacher","Session","Status",""].map(x=><th key={x} className="p-3 text-xs uppercase text-muted">{x}</th>)}</tr></thead><tbody>{assignments.filter(x=>[classMap.get(x.class_id),subjectMap.get(x.subject_id),x.teacher_member_id?memberMap.get(x.teacher_member_id):"",x.session].join(" ").toLowerCase().includes(tableSearch.toLowerCase())).map(x=><tr key={x.id} className="border-t"><td className="p-3 font-bold">{classMap.get(x.class_id)||"Class"}</td><td className="p-3">{subjectMap.get(x.subject_id)||"Subject"}</td><td className="p-3">{x.teacher_member_id?memberMap.get(x.teacher_member_id)||"Teacher":"Not assigned"}</td><td className="p-3">{x.session}</td><td className="p-3">{status(x.teacher_member_id?"Ready":"Pending",x.teacher_member_id?"emerald":"amber")}</td><td className="p-3">{canManage&&<button aria-label="Remove allocation" onClick={()=>void remove(x.id)} className="text-rose-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div>{!assignments.length&&<p className="p-10 text-center text-sm text-muted">No subject allocations yet.</p>}</div></Card>
  </ModulePage>;
}
