import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { Eye, Plus, RefreshCw, Trash2 } from "lucide-react";
import { ModulePage } from "@/components/ModulePage";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { useSchoolProContext } from "@/hooks/useSchoolProContext";
import { schoolSections, status as statusBadge } from "./schoolShared";

type School={id:string;name:string}; type Student={id:string;first_name:string;last_name:string;admission_number:string;class_name:string}; type Subject={id:string;name:string;code:string;class_name:string};
type Component={key:string;label:string;maxScore:number}; type Scheme={id:string;name:string;school_level:string;components:Component[];is_default:boolean};
type Result={id:string;student_id:string;subject_id:string;term:string;session:string;assessment_scheme_id:string|null;assessment_scores:Record<string,number>;total_score:number;status:"draft"|"approved"|"published"};
const starter:Component[]=[{key:"assignment_1",label:"1st CA Assignment",maxScore:10},{key:"assignment_2",label:"2nd CA Assignment",maxScore:10},{key:"test_1",label:"1st CA Test",maxScore:10},{key:"test_2",label:"2nd CA Test",maxScore:10},{key:"exam",label:"Examination",maxScore:60}];
const grade=(score:number)=>score>=80?"A":score>=70?"B":score>=60?"C":score>=50?"D":score>=40?"E":"F";
const safeKey=(label:string,index:number)=>label.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")||`component_${index+1}`;

export function SchoolProResults(){
 const {user,profile}=useAuth();const ctx=useSchoolProContext(); const [schools,setSchools]=useState<School[]>([]); const [schoolId,setSchoolId]=useState(""); const [students,setStudents]=useState<Student[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [schemes,setSchemes]=useState<Scheme[]>([]); const [results,setResults]=useState<Result[]>([]); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
 const [subjectForm,setSubjectForm]=useState({name:"",code:"",className:""}); const [schemeName,setSchemeName]=useState("Nursery & Primary Standard"); const [schemeLevel,setSchemeLevel]=useState("nursery_primary"); const [schemeComponents,setSchemeComponents]=useState<Component[]>(starter); const [editingSchemeId,setEditingSchemeId]=useState("");
 const [scoreForm,setScoreForm]=useState({studentId:"",subjectId:"",term:"First Term",session:"2026/2027",schemeId:"",scores:{} as Record<string,string>}); const [pinStudent,setPinStudent]=useState(""); const [generatedPin,setGeneratedPin]=useState(""); const [gradeScale,setGradeScale]=useState<any[]>([]);
 const userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(" ")||profile.email:"School User";
 const loadSchools=useCallback(async()=>{if(!supabase||!user||ctx.loading)return;if(ctx.schoolId){setSchools([{id:ctx.schoolId,name:ctx.schoolName}]);setSchoolId(ctx.schoolId);}else{setSchools([]);setSchoolId("");}},[user,ctx.loading,ctx.schoolId,ctx.schoolName]);
 const load=useCallback(async()=>{if(!supabase||!schoolId)return;const [a,b,c,d,g]=await Promise.all([supabase.from("schoolpro_students").select("id,first_name,last_name,admission_number,class_name").eq("school_id",schoolId).order("first_name"),supabase.from("schoolpro_subjects").select("id,name,code,class_name").eq("school_id",schoolId).order("name"),supabase.from("schoolpro_assessment_schemes").select("id,name,school_level,components,is_default").eq("school_id",schoolId).order("is_default",{ascending:false}),supabase.from("schoolpro_results").select("id,student_id,subject_id,term,session,assessment_scheme_id,assessment_scores,total_score,status").eq("school_id",schoolId).order("updated_at",{ascending:false}),supabase.from("schoolpro_grade_scale").select("*").eq("school_id",schoolId).order("position")]);const e=a.error||b.error||c.error||d.error||g.error;if(e)setError(e.message);setStudents((a.data||[]) as Student[]);setSubjects((b.data||[]) as Subject[]);const nextSchemes=(c.data||[]) as Scheme[];setSchemes(nextSchemes);setScoreForm(current=>({...current,schemeId:nextSchemes.some(s=>s.id===current.schemeId)?current.schemeId:nextSchemes[0]?.id||"",scores:{}}));const resultRows=(d.data||[]) as unknown as Result[];setResults(resultRows.map(r=>({...r,total_score:Number(r.total_score),assessment_scores:r.assessment_scores||{}})));setGradeScale(g.data||[]);},[schoolId]);
 useEffect(()=>{void loadSchools();},[loadSchools]); useEffect(()=>{void load();},[load]);
 const activeScheme=schemes.find(s=>s.id===scoreForm.schemeId); const componentTotal=schemeComponents.reduce((sum,c)=>sum+Number(c.maxScore||0),0);
 async function addSubject(e:FormEvent){e.preventDefault();if(!supabase||!schoolId)return;setError(null);const {error}=await supabase.from("schoolpro_subjects").insert({school_id:schoolId,name:subjectForm.name,code:subjectForm.code.toUpperCase(),class_name:subjectForm.className});if(error)setError(error.message);else{setSubjectForm({name:"",code:"",className:""});setMessage("Subject created.");await load();}}
 function editScheme(s:Scheme){setEditingSchemeId(s.id);setSchemeName(s.name);setSchemeLevel(s.school_level||"custom");setSchemeComponents(s.components.map(c=>({...c})));}
 async function saveScheme(e:FormEvent){e.preventDefault();if(!supabase||!schoolId)return;if(componentTotal!==100){setError(`Assessment weights currently total ${componentTotal}%. They must total 100%.`);return;}const components=schemeComponents.map((c,i)=>({...c,key:c.key||safeKey(c.label,i),maxScore:Number(c.maxScore)}));const payload={school_id:schoolId,name:schemeName,school_level:schemeLevel,components,is_default:schemes.length===0};const query=editingSchemeId?supabase.from("schoolpro_assessment_schemes").update(payload).eq("id",editingSchemeId):supabase.from("schoolpro_assessment_schemes").insert(payload);const {error}=await query;if(error)setError(error.message);else{setMessage(editingSchemeId?"Assessment scheme updated.":"Custom assessment scheme created.");setEditingSchemeId("");setSchemeName("Custom Assessment");setSchemeComponents(starter.map(c=>({...c})));await load();}}
 async function saveScore(e:FormEvent){e.preventDefault();if(!supabase||!schoolId||!activeScheme)return;setError(null);const assessment_scores=Object.fromEntries(activeScheme.components.map(c=>[c.key,Number(scoreForm.scores[c.key]||0)]));const payload={school_id:schoolId,student_id:scoreForm.studentId,subject_id:scoreForm.subjectId,term:scoreForm.term,session:scoreForm.session,assessment_scheme_id:activeScheme.id,assessment_scores,updated_at:new Date().toISOString()};const {error}=await supabase.from("schoolpro_results").upsert(payload,{onConflict:"student_id,subject_id,term,session"});if(error)setError(error.message);else{setMessage("Assessment saved and total calculated automatically.");setScoreForm({...scoreForm,studentId:"",subjectId:"",scores:{}});await load();}}
 async function generatePin(){if(!supabase||!pinStudent)return;setGeneratedPin("");const {data,error}=await supabase.rpc("create_schoolpro_result_pin",{target_student:pinStudent,target_term:scoreForm.term,target_session:scoreForm.session});if(error)setError(error.message);else{setGeneratedPin(String(data));setMessage("A new result access PIN was generated. Copy it now; only its secure hash is stored.");}}
 async function changeStatus(item:Result,next:Result["status"]){if(!supabase)return;if(next==="approved"){const {error}=await supabase.rpc("review_schoolpro_result",{p_result:item.id,p_status:"approved",p_notes:null});if(error)setError(error.message);else{setMessage("Result approved through the controlled review workflow.");await load();}return;}if(next==="published"){setError("Publish approved results from the Broadsheet so publication is controlled by class, term and session.");return;}}
 const studentMap=useMemo(()=>new Map(students.map(s=>[s.id,s])),[students]),subjectMap=useMemo(()=>new Map(subjects.map(s=>[s.id,s])),[subjects]),schemeMap=useMemo(()=>new Map(schemes.map(s=>[s.id,s])),[schemes]); const published=results.filter(r=>r.status==="published").length; const average=results.length?results.reduce((s,r)=>s+r.total_score,0)/results.length:0;
 return <ModulePage product="schoolpro" sections={schoolSections} title="Results & Broadsheets" description="Use the Nigerian nursery and primary 40% continuous assessment + 60% examination structure, or create any assessment mix totaling 100%." userName={userName} userRole="School Administrator" primaryAction="Live Results" metrics={[{label:"Score Records",value:String(results.length)},{label:"Average",value:`${average.toFixed(1)}%`},{label:"Schemes",value:String(schemes.length)},{label:"Published",value:String(published)}]}>
  {(error||message)&&<div className={`rounded-xl border p-3 text-sm ${error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error||message}</div>}
  <div className="flex items-center justify-between gap-3"><select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="rounded-lg border border-border bg-white px-3 py-2 text-sm">{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button variant="secondary" size="sm" leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>void load()}>Refresh</Button></div>
  {!schoolId&&<Card><p className="text-sm text-muted">Create a school workspace before entering results.</p></Card>}
  {schoolId&&<Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Assessment setup</h3><p className="mt-1 text-sm text-muted">The default is 10% + 10% assignments, 10% + 10% tests and 60% examination. You may rename, add or remove components, but the total must remain 100%.</p></div><div className={`rounded-full px-3 py-1 text-sm font-bold ${componentTotal===100?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>Total: {componentTotal}%</div></div><form onSubmit={saveScheme} className="mt-4 space-y-3"><select value={schemeLevel} onChange={e=>setSchemeLevel(e.target.value)} className="w-full rounded-lg border p-2 text-sm"><option value="nursery_primary">Nursery & Primary</option><option value="junior_secondary">Junior Secondary (JSS)</option><option value="senior_secondary">Senior Secondary (SSS)</option><option value="custom">Custom</option></select><input required value={schemeName} onChange={e=>setSchemeName(e.target.value)} placeholder="Scheme name" className="w-full rounded-lg border p-2 text-sm"/><div className="grid gap-2">{schemeComponents.map((component,index)=><div key={`${component.key}-${index}`} className="grid grid-cols-[1fr_110px_38px] gap-2"><input required value={component.label} onChange={e=>setSchemeComponents(items=>items.map((c,i)=>i===index?{...c,label:e.target.value,key:editingSchemeId?c.key:safeKey(e.target.value,i)}:c))} className="rounded-lg border p-2 text-sm"/><input required type="number" min="1" max="100" value={component.maxScore} onChange={e=>setSchemeComponents(items=>items.map((c,i)=>i===index?{...c,maxScore:Number(e.target.value)}:c))} className="rounded-lg border p-2 text-sm" aria-label={`${component.label} percentage`}/><button type="button" onClick={()=>setSchemeComponents(items=>items.filter((_,i)=>i!==index))} className="grid place-items-center rounded-lg border text-rose-600" aria-label="Remove component"><Trash2 className="h-4 w-4"/></button></div>)}</div><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" size="sm" leftIcon={<Plus className="h-4 w-4"/>} onClick={()=>setSchemeComponents(items=>[...items,{key:`component_${items.length+1}`,label:"New Assessment",maxScore:0}])}>Add Component</Button><Button size="sm" disabled={componentTotal!==100}>{editingSchemeId?"Update Scheme":"Save Custom Scheme"}</Button>{editingSchemeId&&<Button type="button" variant="ghost" size="sm" onClick={()=>{setEditingSchemeId("");setSchemeName("Custom Assessment");setSchemeComponents(starter.map(c=>({...c})));}}>Cancel</Button>}</div></form><div className="mt-4 flex flex-wrap gap-2">{schemes.map(s=><button key={s.id} onClick={()=>editScheme(s)} className="rounded-full border border-purple-200 bg-purple-50 px-3 py-1 text-xs font-semibold text-purple-700">{s.name}{s.is_default?" · Default":""}</button>)}</div></Card>}
  {schoolId&&<Card><h3 className="font-bold">Grade Scale</h3><p className="mt-1 text-sm text-muted">Configure the school's score ranges and remarks. These ranges are intended to replace fixed A–F assumptions in generated results.</p><div className="mt-3 grid gap-2">{gradeScale.map((g:any)=><div key={g.id} className="grid grid-cols-4 gap-2 text-sm"><b>{g.label}</b><span>{g.min_score}–{g.max_score}</span><span className="col-span-2">{g.remark||'—'}</span></div>)}{!gradeScale.length&&<p className="text-sm text-amber-700">No custom grade scale configured yet.</p>}</div></Card>}
  {schoolId&&<div className="grid grid-cols-1 gap-5 xl:grid-cols-2"><Card><h3 className="font-bold">Add Subject</h3><form onSubmit={addSubject} className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3"><input required value={subjectForm.name} onChange={e=>setSubjectForm({...subjectForm,name:e.target.value})} placeholder="Subject name" className="rounded-lg border p-2 text-sm"/><input required value={subjectForm.code} onChange={e=>setSubjectForm({...subjectForm,code:e.target.value})} placeholder="Code" className="rounded-lg border p-2 text-sm"/><input required value={subjectForm.className} onChange={e=>setSubjectForm({...subjectForm,className:e.target.value})} placeholder="Class" className="rounded-lg border p-2 text-sm"/><Button className="sm:col-span-3" leftIcon={<Plus className="h-4 w-4"/>}>Add Subject</Button></form></Card><Card><h3 className="font-bold">Enter or Update Assessment</h3><form onSubmit={saveScore} className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><select required value={scoreForm.studentId} onChange={e=>setScoreForm({...scoreForm,studentId:e.target.value})} className="rounded-lg border p-2 text-sm"><option value="">Student</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select><select required value={scoreForm.subjectId} onChange={e=>setScoreForm({...scoreForm,subjectId:e.target.value})} className="rounded-lg border p-2 text-sm"><option value="">Subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name} · {s.class_name}</option>)}</select><input required value={scoreForm.term} onChange={e=>setScoreForm({...scoreForm,term:e.target.value})} className="rounded-lg border p-2 text-sm"/><input required value={scoreForm.session} onChange={e=>setScoreForm({...scoreForm,session:e.target.value})} className="rounded-lg border p-2 text-sm"/><select required value={scoreForm.schemeId} onChange={e=>setScoreForm({...scoreForm,schemeId:e.target.value,scores:{}})} className="rounded-lg border p-2 text-sm sm:col-span-2"><option value="">Assessment scheme</option>{schemes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{activeScheme?.components.map(c=><label key={c.key} className="text-xs font-semibold text-muted">{c.label} / {c.maxScore}<input required type="number" min="0" max={c.maxScore} step="0.01" value={scoreForm.scores[c.key]||""} onChange={e=>setScoreForm({...scoreForm,scores:{...scoreForm.scores,[c.key]:e.target.value}})} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label>)}<Button className="sm:col-span-2">Save Assessment</Button></form></Card></div>}
  {schoolId&&<Card padding="none" className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="sticky top-0 z-10 bg-gray-50 shadow-sm"><tr>{["Student","Subject","Term","Assessment breakdown","Total","Grade","Status","Actions"].map(h=><th key={h} className="p-3 text-xs uppercase text-muted">{h}</th>)}</tr></thead><tbody>{results.map(r=>{const s=studentMap.get(r.student_id),sub=subjectMap.get(r.subject_id),scheme=schemeMap.get(r.assessment_scheme_id||"");return <tr key={r.id} className="border-t"><td className="p-3 font-semibold">{s?`${s.first_name} ${s.last_name}`:"Student"}</td><td className="p-3">{sub?.name||"Subject"}</td><td className="p-3">{r.term}<br/><span className="text-xs text-muted">{r.session}</span></td><td className="p-3"><div className="min-w-48 text-xs">{scheme?.components.map(c=><span key={c.key} className="mr-2 inline-block">{c.label}: <b>{r.assessment_scores[c.key]??0}/{c.maxScore}</b></span>)||"Legacy assessment"}</div></td><td className="p-3 font-bold">{r.total_score}</td><td className="p-3 font-bold">{grade(r.total_score)}</td><td className="p-3">{statusBadge(r.status,r.status==="draft"?"amber":"emerald")}</td><td className="p-3"><div className="flex gap-2">{r.status==="draft"&&<button className="text-xs font-bold text-purple-700" onClick={()=>void changeStatus(r,"approved")}>Approve</button>}{r.status==="approved"&&<Link className="text-xs font-bold text-emerald-700" to="/schoolpro/broadsheet">Publish via Broadsheet</Link>}<Link className="text-purple-700" to={`/schoolpro/report-card?student=${r.student_id}&term=${encodeURIComponent(r.term)}&session=${encodeURIComponent(r.session)}`}><Eye className="h-4 w-4"/></Link></div></td></tr>})}</tbody></table>{!results.length&&<p className="py-10 text-center text-sm text-muted">No scores entered yet.</p>}</div></Card>}
 </ModulePage>;
}
