import {customerMessage} from '@/lib/customerMessage';
import{useState}from'react';import{Link}from'react-router-dom';import{PageShell}from'@/components/PageShell';import{Card}from'@/components/ui/Card';import{Button}from'@/components/ui/Button';import{supabase}from'@/lib/supabase';import{useAuth}from'@/context/AuthContext';
const pages=['Home','About','Academics','Admissions','Facilities','Gallery','News & Events','Staff & Leadership','Contact','Apply Online','Result Checker','Portal Login'];const modules=['Online Admission','Entrance CBT','Admission Letters','Fees & Payments','Custom Result Cards','School Email','SMS/Email Communication','Advanced Analytics','White Label','Custom Domain'];
export function SchoolProCustomRequest(){const{user}=useAuth();const[f,setF]=useState<any>({school_name:'',contact_name:'',email:'',phone:'',existing_domain:'',desired_domain:'',motto:'',primary_color:'#6d28d9',secondary_color:'#0f172a',package_interest:'custom',notes:'',requested_pages:pages,requested_modules:modules}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const toggle=(k:string,v:string)=>setF({...f,[k]:f[k].includes(v)?f[k].filter((x:string)=>x!==v):[...f[k],v]});async function submit(){
if(busy)return;
if(!supabase||!user)return setMsg('Please sign in before submitting a managed SchoolPro request.');
const schoolName=f.school_name.trim(),contactName=f.contact_name.trim(),email=f.email.trim(),phone=f.phone.trim();
if(!schoolName||!contactName||!email||!phone)return setMsg('Enter the school name, contact person, email and phone.');
if(!/^[^\s@]+@[^\s@]+\\.[^\s@]+$/.test(email))return setMsg('Enter a valid email address.');
setBusy(true);setMsg('');
try{const r=await supabase.from('schoolpro_custom_requests').insert({...f,school_name:schoolName,contact_name:contactName,email,phone,requester_user_id:user.id,status:'submitted'});setMsg(customerMessage(r.error?.message||'Request submitted to IHLink. Our team can now review, quote and provision your managed school website.'));}
catch{setMsg('The request could not be submitted. Please try again.');}finally{setBusy(false);}
}return <PageShell product="schoolpro"><main className="mx-auto max-w-5xl px-6 py-12"><h1 className="text-4xl font-black">Request Custom SchoolPro</h1><p className="mt-3 max-w-3xl text-muted">Request a school-branded website and portal while IHLink manages the platform, infrastructure, maintenance, security, updates and subscription.</p><Card className="mt-7"><div className="grid gap-3 md:grid-cols-2">{[['school_name','School name'],['contact_name','Contact person'],['email','Email'],['phone','Phone'],['existing_domain','Existing domain (optional)'],['desired_domain','Desired domain'],['motto','School motto']].map(([k,l])=><input key={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} placeholder={l} className="rounded-xl border p-3"/>)}<select value={f.package_interest} onChange={e=>setF({...f,package_interest:e.target.value})} className="rounded-xl border p-3"><option value="professional">Professional</option><option value="premium">Premium</option><option value="custom">Custom / White Label</option></select></div><h2 className="mt-7 font-bold">Website pages</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{pages.map(x=><label key={x} className="rounded-lg border p-3 text-sm"><input type="checkbox" checked={f.requested_pages.includes(x)} onChange={()=>toggle('requested_pages',x)} className="mr-2"/>{x}</label>)}</div><h2 className="mt-7 font-bold">Premium capabilities</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{modules.map(x=><label key={x} className="rounded-lg border p-3 text-sm"><input type="checkbox" checked={f.requested_modules.includes(x)} onChange={()=>toggle('requested_modules',x)} className="mr-2"/>{x}</label>)}</div><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})} placeholder="Describe your branding, migration or special requirements" className="mt-5 min-h-28 w-full rounded-xl border p-3"/><Button className="mt-4" disabled={busy} onClick={()=>void submit()}>{busy?'Submitting…':'Submit Custom SchoolPro Request'}</Button>{msg&&<p role="status" className="mt-4 text-sm font-semibold">{msg}</p>}</Card><p className="mt-6 text-sm text-muted">Need to discuss requirements first? <Link className="font-semibold text-purple-700" to="/schoolpro/book-demo">Book a demo</Link>.</p></main></PageShell>}