import {useEffect,useMemo,useState} from 'react';import {ModulePage} from '@/components/ModulePage';import {schoolSections,status} from './schoolShared';import {supabase} from '@/lib/supabase';import {useSchoolProContext} from '@/hooks/useSchoolProContext';import {useAuth} from '@/context/AuthContext';import {Card} from '@/components/ui/Card';import {Button} from '@/components/ui/Button';import {Search} from 'lucide-react';
const defs:Record<string,{title:string;description:string;action:string;table:string;fields:{key:string;label:string;type?:string}[]}>={
admissions:{title:'Admissions',description:'Manage applications and enrolment decisions.',action:'New Application',table:'schoolpro_admissions',fields:[{key:'applicant_name',label:'Applicant name'},{key:'guardian_name',label:'Guardian name'},{key:'guardian_contact',label:'Guardian contact'},{key:'class_applied',label:'Class applied'}]},
timetable:{title:'Timetable',description:'Build and maintain class timetable entries.',action:'Add Timetable Entry',table:'schoolpro_timetable_entries',fields:[{key:'weekday',label:'Weekday (1-7)',type:'number'},{key:'starts_at',label:'Start time',type:'time'},{key:'ends_at',label:'End time',type:'time'},{key:'room',label:'Room'}]},
assignments:{title:'Assignments',description:'Create and track classroom assignments.',action:'New Assignment',table:'schoolpro_assignments',fields:[{key:'title',label:'Title'},{key:'instructions',label:'Instructions'},{key:'due_at',label:'Due date',type:'datetime-local'}]},
cbt:{title:'Computer-Based Tests',description:'Create timed CBT assessments.',action:'Create Test',table:'schoolpro_cbt_tests',fields:[{key:'title',label:'Test title'},{key:'duration_minutes',label:'Duration minutes',type:'number'},{key:'total_marks',label:'Total marks',type:'number'}]},
library:{title:'Library',description:'Manage library catalogue and availability.',action:'Add Book',table:'schoolpro_library_books',fields:[{key:'title',label:'Book title'},{key:'author',label:'Author'},{key:'isbn',label:'ISBN'},{key:'copies',label:'Copies',type:'number'}]},
transport:{title:'Transportation',description:'Manage routes, vehicles and drivers.',action:'Add Route',table:'schoolpro_transport_routes',fields:[{key:'name',label:'Route name'},{key:'vehicle',label:'Vehicle'},{key:'driver_name',label:'Driver'},{key:'driver_phone',label:'Driver phone'}]},
hostel:{title:'Hostel',description:'Manage hostels, rooms and capacity.',action:'Add Room',table:'schoolpro_hostel_rooms',fields:[{key:'hostel_name',label:'Hostel'},{key:'room',label:'Room'},{key:'capacity',label:'Capacity',type:'number'},{key:'fee',label:'Fee',type:'number'}]},
inventory:{title:'Inventory & Assets',description:'Track assets and stock.',action:'Add Asset',table:'schoolpro_inventory_assets',fields:[{key:'name',label:'Asset name'},{key:'category',label:'Category'},{key:'quantity',label:'Quantity',type:'number'},{key:'location',label:'Location'}]},
discipline:{title:'Discipline',description:'Track incidents and follow-up actions.',action:'Log Incident',table:'schoolpro_discipline_records',fields:[{key:'incident',label:'Incident'},{key:'action_taken',label:'Action taken'}]},
announcements:{title:'Communication Centre',description:'Publish targeted school announcements.',action:'New Announcement',table:'schoolpro_announcements',fields:[{key:'title',label:'Title'},{key:'body',label:'Message'},{key:'audience',label:'Audience'}]},
};
export function SchoolProModulePage({module}:{module:string}){const d=defs[module];const ctx=useSchoolProContext();const {profile,user}=useAuth();const [rows,setRows]=useState<any[]>([]),[query,setQuery]=useState(''),[form,setForm]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
async function load(){if(!d||!supabase||!ctx.schoolId)return;const r=await supabase.from(d.table).select('*').eq('school_id',ctx.schoolId).order('created_at',{ascending:false});setRows(r.data||[]);if(r.error)setNotice(r.error.message)}
useEffect(()=>{void load()},[ctx.schoolId,module]);
const filtered=useMemo(()=>rows.filter(r=>!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
async function save(){if(!supabase||!ctx.schoolId||!d)return;const payload:any={school_id:ctx.schoolId};for(const f of d.fields){const v=form[f.key];if(v!=='')payload[f.key]=f.type==='number'?Number(v):v;}if(['assignments','cbt','discipline'].includes(module))payload.created_by=user?.id;if(module==='announcements')payload.created_by=user?.id;const r=await supabase.from(d.table).insert(payload);setNotice(r.error?.message||'Saved successfully.');if(!r.error){setForm({});await load();}}
if(!d)return <ModulePage product="schoolpro" sections={schoolSections} title="SchoolPro Module" description="This module is being configured." userName={ctx.schoolName} userRole={ctx.role}/>;
if(ctx.loading)return <div className="min-h-screen grid place-items-center">Loading…</div>;if(!ctx.schoolId&&profile?.role!=='super_admin')return <ModulePage product="schoolpro" sections={schoolSections} title={d.title} description={d.description} userName="SchoolPro" userRole="No school access"><Card>School access required.</Card></ModulePage>;
return <ModulePage product="schoolpro" sections={schoolSections} title={d.title} description={d.description} userName={ctx.schoolName} userRole={ctx.role} metrics={[{label:'Records',value:String(rows.length)},{label:'Visible',value:String(filtered.length)},{label:'Data',value:'Live database'},{label:'Access',value:ctx.role}]}>
<Card><h3 className="font-bold">{d.action}</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{d.fields.map(f=><input key={f.key} type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm(x=>({...x,[f.key]:e.target.value}))} placeholder={f.label} className="rounded-lg border p-2.5 text-sm"/>)}<Button onClick={()=>void save()}>Save</Button>{notice&&<p className="self-center text-sm text-muted">{notice}</p>}</div></Card>
<Card className="mt-5"><div className="relative mb-4"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Search "+d.title.toLowerCase()+"…"} className="w-full rounded-xl border py-2.5 pl-10 pr-3 text-sm"/></div><div className="max-h-[60vh] overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="sticky-table-header"><tr>{d.fields.map(f=><th key={f.key} className="px-3 py-3 text-left">{f.label}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t">{d.fields.map(f=><td key={f.key} className="px-3 py-3">{String(r[f.key]??'—')}</td>)}</tr>)}</tbody></table>{!filtered.length&&<p className="p-8 text-center text-sm text-muted">No matching records.</p>}</div></Card></ModulePage>}