import {useEffect,useState} from 'react';
import {ModulePage} from '@/components/ModulePage';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {SchoolClassSelect} from '@/components/SchoolClassSelect';
import {AcademicPeriodSelect} from '@/components/AcademicPeriodSelect';
import {useSchoolProContext} from '@/hooks/useSchoolProContext';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
import {customerMessage} from '@/lib/customerMessage';
import {printSchoolDocument} from '@/lib/nativePrint';
import {schoolSection} from '@/lib/schoolClassFilters';
import {schoolSections} from './schoolShared';
type Note={id?:string;title:string;class_id:string|null;subject_id:string|null;lesson_date:string;term:string;session:string;week:number|null;duration_minutes:number|null;content:string;plan:Record<string,string>;status:string;created_by?:string;review_comment?:string|null};
const fields=[['objectives','Learning objectives'],['previous_knowledge','Previous knowledge'],['materials','Teaching materials'],['references','References'],['introduction','Introduction / starter'],['development','Teaching steps / teacher activities'],['learner_activity','Learner activities / guided practice'],['evaluation','Evaluation / checks for understanding'],['conclusion','Conclusion / recap'],['homework','Assignment / homework'],['reflection','Reflection / follow-up']];
const empty=():Note=>({title:'',class_id:null,subject_id:null,lesson_date:'',term:'',session:'',week:null,duration_minutes:40,content:'',plan:{},status:'draft'});
const input='mt-1 w-full min-w-0 rounded-xl border bg-white p-3 text-sm';
const label=(s:string)=>({draft:'Draft',submitted:'Awaiting review',approved:'Approved',changes_requested:'Changes requested'}[s]||s.replaceAll('_',' '));
export function SchoolProLessonNotes(){
const ctx=useSchoolProContext(),{user}=useAuth();
const [rows,setRows]=useState<Note[]>([]),[classes,setClasses]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[allocations,setAllocations]=useState<any[]>([]),[member,setMember]=useState('');
const [form,setForm]=useState<Note>(empty),[preview,setPreview]=useState<Note|null>(null),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[filterClass,setFilterClass]=useState(''),[filterSection,setFilterSection]=useState(''),[filterStatus,setFilterStatus]=useState('');
const leader=['Proprietor','Super Administrator','administrator','head_teacher','vice_principal'].includes(ctx.role);
async function reload(){if(!supabase||!ctx.schoolId)return;const r=await supabase.from('schoolpro_lesson_notes').select('*').eq('school_id',ctx.schoolId).order('created_at',{ascending:false}).limit(500);if(r.error)setMessage(customerMessage(r.error.message));else setRows(r.data||[]);}
useEffect(()=>{let current=true;setRows([]);setClasses([]);setSubjects([]);setAllocations([]);setMember('');setForm(empty());setPreview(null);setLoading(true);setMessage('');setFilterClass('');setFilterSection('');
if(!supabase||!ctx.schoolId){setLoading(false);return;}const db=supabase;
void Promise.all([db.from('schoolpro_lesson_notes').select('*').eq('school_id',ctx.schoolId).order('created_at',{ascending:false}).limit(500),db.from('schoolpro_classes').select('id,name,arm,level,form_teacher_id').eq('school_id',ctx.schoolId),db.from('schoolpro_subjects').select('id,name').eq('school_id',ctx.schoolId),db.from('schoolpro_subject_assignments').select('class_id,subject_id,teacher_member_id').eq('school_id',ctx.schoolId),db.from('schoolpro_members').select('id').eq('school_id',ctx.schoolId).eq('user_id',user?.id||'').maybeSingle()]).then(([a,b,c,d,e])=>{if(!current)return;setRows(a.data||[]);setClasses(b.data||[]);setSubjects(c.data||[]);setAllocations(d.data||[]);setMember(e.data?.id||'');setLoading(false);if(a.error||b.error||c.error||d.error||e.error)setMessage('Lesson notes could not be fully loaded. Please refresh and try again.');}).catch(()=>{if(current){setLoading(false);setMessage('Lesson notes could not be loaded. Please try again.');}});return()=>{current=false};},[ctx.schoolId,user?.id]);
const availableSubjects=subjects.filter(s=>leader||classes.find(c=>c.id===form.class_id)?.form_teacher_id===member||allocations.some(a=>a.class_id===form.class_id&&a.subject_id===s.id&&a.teacher_member_id===member));
async function save(status:'draft'|'submitted'){
if(busy||!supabase||!ctx.schoolId)return;
if(!leader&&(!form.class_id||!form.subject_id)){setMessage('Select your assigned class and subject before saving.');return;}
if(!form.title.trim()){setMessage('Enter the lesson topic.');return;}
if(!Number.isInteger(form.duration_minutes)||Number(form.duration_minutes)<1||Number(form.duration_minutes)>480||form.week!==null&&(!Number.isInteger(form.week)||form.week<1||form.week>53)){setMessage('Check the week number and lesson duration.');return;}
if(status==='submitted'&&(!form.class_id||!form.subject_id||!form.lesson_date||!form.term||!form.session||!form.content.trim()||!form.plan.objectives?.trim())){setMessage('Complete class, subject, date, period, objectives and lesson content before submitting.');return;}
setBusy(true);setMessage('');try{
const data={school_id:ctx.schoolId,title:form.title.trim(),class_id:form.class_id,subject_id:form.subject_id,lesson_date:form.lesson_date||null,term:form.term||null,session:form.session||null,week:form.week,duration_minutes:form.duration_minutes,content:form.content,plan:form.plan,status};
const r=form.id?await supabase.from('schoolpro_lesson_notes').update(data).eq('school_id',ctx.schoolId).eq('id',form.id).in('status',['draft','changes_requested']).select('id'):await supabase.from('schoolpro_lesson_notes').insert(data).select('id');
if(r.error){setMessage(customerMessage(r.error.message));return;}if(!r.data?.length){setMessage('This lesson changed. Refresh before editing.');await reload();return;}setForm(empty());setMessage(status==='submitted'?'Lesson submitted for school review.':'Lesson draft saved.');await reload();
}catch{setMessage('The lesson could not be saved. Please try again.');}finally{setBusy(false);}}
async function decide(status:'approved'|'changes_requested'){
if(!leader||!preview?.id||!supabase||busy)return;if(status==='changes_requested'&&!feedback.trim()){setMessage('Explain the changes needed.');return;}setBusy(true);
try{const r=await supabase.from('schoolpro_lesson_notes').update({status,review_comment:feedback.trim()||null}).eq('school_id',ctx.schoolId!).eq('id',preview.id).eq('status','submitted').select('id');if(r.error){setMessage(customerMessage(r.error.message));return;}setMessage(r.data?.length?(status==='approved'?'Lesson approved.':'Changes requested.'):'This lesson has already changed. Refresh before reviewing.');setPreview(null);await reload();}catch{setMessage('The review could not be saved.');}finally{setBusy(false);}}
async function remove(row:Note){if(!row.id||busy||!supabase||!confirm('Delete this unapproved lesson draft?'))return;setBusy(true);try{const r=await supabase.from('schoolpro_lesson_notes').delete().eq('school_id',ctx.schoolId!).eq('id',row.id).in('status',['draft','changes_requested']).select('id');setMessage(r.error?customerMessage(r.error.message):r.data?.length?'Lesson draft deleted.':'The lesson changed. Please refresh.');if(!r.error)await reload();}catch{setMessage('The draft could not be deleted.');}finally{setBusy(false);}}
const visible=rows.filter(r=>(!filterClass||r.class_id===filterClass)&&(!filterSection||classes.some(c=>c.id===r.class_id&&schoolSection(c.level,c.name)===filterSection))&&(!filterStatus||r.status===filterStatus)&&(!search||[r.title,r.content,r.term,r.session,subjects.find(s=>s.id===r.subject_id)?.name].join(' ').toLowerCase().includes(search.toLowerCase())));
function open(row:Note){setPreview(row);setFeedback(row.review_comment||'');}
return <ModulePage product="schoolpro" sections={schoolSections} title="Lesson Notes" description="Plan teaching, submit lessons for review and keep a clear classroom record." userName={ctx.schoolName} userRole={ctx.role}>
{message&&<p role="status" className="mb-4 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}
<div className="grid min-w-0 gap-5 xl:grid-cols-2"><Card><h2 className="text-lg font-bold">{form.id?'Edit lesson draft':'Plan a lesson'}</h2><p className="mt-1 text-sm text-muted">Submitted notes wait for school review. Approved notes remain in the school record.</p>
<div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Topic / lesson title<input maxLength={250} className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
<SchoolClassSelect classes={classes} value={form.class_id||''} onChange={id=>setForm({...form,class_id:id||null,subject_id:null})}/><label className="text-sm font-semibold">Subject<select className={input} value={form.subject_id||''} onChange={e=>setForm({...form,subject_id:e.target.value||null})}><option value="">Select subject</option>{availableSubjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
<AcademicPeriodSelect kind="term" label="Term" value={form.term||''} onChange={e=>setForm({...form,term:e.target.value})}/><AcademicPeriodSelect kind="session" label="Academic session" value={form.session||''} onChange={e=>setForm({...form,session:e.target.value})}/>
<label className="text-sm font-semibold">Lesson date<input className={input} type="date" value={form.lesson_date||''} onChange={e=>setForm({...form,lesson_date:e.target.value})}/></label><label className="text-sm font-semibold">Week<input className={input} type="number" min={1} max={53} value={form.week??''} onChange={e=>setForm({...form,week:e.target.value?Number(e.target.value):null})}/></label><label className="text-sm font-semibold">Duration (minutes)<input className={input} type="number" min={1} max={480} value={form.duration_minutes??''} onChange={e=>setForm({...form,duration_minutes:e.target.value?Number(e.target.value):null})}/></label>
</div><div className="mt-4 space-y-3"><label className="block text-sm font-semibold">Lesson content<textarea rows={7} className={input} value={form.content||''} onChange={e=>setForm({...form,content:e.target.value})}/></label>{fields.map(([key,name])=><label key={key} className="block text-sm font-semibold">{name}<textarea rows={3} className={input} value={form.plan?.[key]||''} onChange={e=>setForm({...form,plan:{...form.plan,[key]:e.target.value}})}/></label>)}</div>
<div className="mt-5 flex flex-wrap gap-2"><Button disabled={busy||loading} onClick={()=>void save('draft')}>{busy?'Saving…':'Save draft'}</Button><Button disabled={busy||loading} variant="secondary" onClick={()=>void save('submitted')}>Submit for review</Button><Button disabled={busy} variant="secondary" onClick={()=>open({...form,status:'draft'})}>Preview draft</Button>{form.id&&<Button disabled={busy} variant="secondary" onClick={()=>setForm(empty())}>Cancel editing</Button>}</div>
</Card><Card><h2 className="text-lg font-bold">Saved lessons</h2><div className="mt-3 space-y-3"><SchoolClassSelect classes={classes} value={filterClass} emptyLabel="All classes" onSectionChange={setFilterSection} onChange={setFilterClass}/><label className="block text-sm font-semibold">Status<select className={input} value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">All statuses</option>{['draft','submitted','approved','changes_requested'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><input aria-label="Search lesson notes" placeholder="Search topic or subject" className={input} value={search} onChange={e=>setSearch(e.target.value)}/></div>
{loading?<p className="mt-4">Loading lessons…</p>:!visible.length?<p className="mt-4 text-sm text-muted">No matching lesson notes.</p>:<div className="mt-4 space-y-3">{visible.map(row=><article key={row.id} className="min-w-0 rounded-xl border p-3"><h3 className="break-words font-bold">{row.title}</h3><p className="mt-1 text-sm">{classes.find(c=>c.id===row.class_id)?.name||'Class not set'} · {subjects.find(s=>s.id===row.subject_id)?.name||'Subject not set'}</p><p className="mt-1 text-xs text-muted">{row.lesson_date||'Date not set'} · {row.term} {row.session} · {label(row.status)}</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>open(row)}>Preview{leader&&row.status==='submitted'?' and review':''}</Button><Button disabled={busy} variant="secondary" onClick={()=>{setForm({...empty(),...row,id:undefined,created_by:undefined,status:'draft',review_comment:null,plan:{...row.plan}});setPreview(null);}}>Use a copy</Button>{['draft','changes_requested'].includes(row.status)&&(leader||row.created_by===user?.id)&&<><Button disabled={busy} variant="secondary" onClick={()=>{setForm({...empty(),...row,plan:row.plan||{}});setPreview(null);}}>Edit</Button><button disabled={busy} className="text-sm text-rose-700" onClick={()=>void remove(row)}>Delete draft</button></>}</div></article>)}</div>}
</Card></div>
{preview&&<Card className="mt-5"><div className="mb-4 flex flex-wrap gap-2"><Button onClick={()=>void printSchoolDocument({name:[ctx.schoolName,classes.find(c=>c.id===preview.class_id)?.name,preview.title,'Lesson-Note'].filter(Boolean).join('-'),paperSize:'A4'})}>Print / Save PDF</Button><Button variant="secondary" onClick={()=>setPreview(null)}>Close preview</Button></div>
<article className="print-document min-w-0 break-words"><h2 className="text-xl font-bold">{ctx.schoolName}</h2><h3 className="mt-2 text-lg font-bold">{preview.title}</h3><p className="mt-2 text-sm">{classes.find(c=>c.id===preview.class_id)?.name} · {subjects.find(s=>s.id===preview.subject_id)?.name} · {preview.lesson_date}</p><p className="text-sm">{preview.term} · {preview.session} · Week {preview.week||'—'} · {preview.duration_minutes||'—'} minutes · {label(preview.status)}</p><section className="mt-4"><h4 className="font-bold">Lesson content</h4><p className="whitespace-pre-wrap text-sm">{preview.content}</p></section>{fields.map(([key,name])=>preview.plan?.[key]&&<section key={key} className="mt-4"><h4 className="font-bold">{name}</h4><p className="whitespace-pre-wrap text-sm">{preview.plan[key]}</p></section>)}{preview.review_comment&&<section className="mt-4"><h4 className="font-bold">School review</h4><p className="whitespace-pre-wrap text-sm">{preview.review_comment}</p></section>}</article>
{leader&&preview.id&&preview.status==='submitted'&&<div className="mt-5 border-t pt-4"><label className="block text-sm font-semibold">Review feedback<textarea rows={3} className={input} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void decide('approved')}>Approve lesson</Button><Button disabled={busy} variant="secondary" onClick={()=>void decide('changes_requested')}>Request changes</Button></div></div>}
</Card>}</ModulePage>;
}
