import {buildClassResultsWorkbook} from '@/lib/classResultsWorkbook';
import {useCallback,useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Button} from '@/components/ui/Button';
import {supabase} from '@/lib/supabase';
import {useSchoolProContext} from '@/hooks/useSchoolProContext';
import {SchoolProReportCard} from './SchoolProReportCard';
import {printSchoolDocument} from '@/lib/nativePrint';
import {saveSchoolFile,XLSX_MIME,schoolFileName} from '@/lib/schoolDownloads';
export function SchoolProClassResultsPrint(){
 const ctx=useSchoolProContext(),[params]=useSearchParams();const classId=params.get('class')||'',term=params.get('term')||'',session=params.get('session')||'',selection=params.get('students')||'';
 const [ready,setReady]=useState<Record<string,boolean>>({});const reportReady=useCallback((id:string,success:boolean)=>setReady(r=>r[id]===success?r:{...r,[id]:success}),[]);
 const [workbooks,setWorkbooks]=useState<{student:any;results:any[]}[]>([]),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState('');
 const [students,setStudents]=useState<{id:string;class_name:string}[]>([]),[error,setError]=useState(''),[skipped,setSkipped]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let current=true;setStudents([]);setWorkbooks([]);setReady({});setSkipped(0);setError('');setLoading(true);if(ctx.loading)return;
 void(async()=>{if(!supabase||!ctx.schoolId||!term||!session)throw Error('Choose a term and session first.');const db=supabase;
 let classes=db.from('schoolpro_classes').select('id').eq('school_id',ctx.schoolId);if(classId&&classId!=='all')classes=classes.eq('id',classId);const cl=await classes;if(cl.error)throw Error('Your classes could not be loaded.');
 let ids=(cl.data||[]).map(c=>c.id);if(!ids.length)throw Error('No authorised classes are available.');
 // Broadsheet permission must be checked separately for every class before loading any batch.
 const authorised=[];for(const id of ids){const check=await db.rpc('schoolpro_broadsheet',{p_school:ctx.schoolId,p_class:id,p_term:term,p_session:session});if(check.error){if(classId!=='all')throw Error('You do not have permission to print these class results.');}else authorised.push(id);}ids=authorised;if(!ids.length)throw Error('No authorised classes are available.');
 let studentQuery=db.from('schoolpro_students').select('id,class_name,first_name,last_name,admission_number').eq('school_id',ctx.schoolId).in('class_id',ids).eq('status','active');if(selection){const selected=selection.split(',');if(selected.some(id=>!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)))throw Error('Select students from the class broadsheet.');studentQuery=studentQuery.in('id',selected);}const st=await studentQuery.order('class_name').order('last_name');if(st.error)throw Error('Students could not be loaded.');
 let omitted=0;const printable=[],reports=[];for(const s of st.data||[]){const r=await db.rpc('schoolpro_printable_result',{p_student:s.id,p_term:term,p_session:session});if(r.error){const access=await db.rpc('schoolpro_result_access',{target_student:s.id,target_term:term,target_session:session}).maybeSingle();if(!access.error&&(access.data as any)?.allowed===false){omitted++;continue;}throw Error('Published reports could not be loaded. Your stored results are unchanged.');}if(r.data?.length){printable.push(s);reports.push({student:s,results:r.data});}}
 if(current){setStudents(printable);setWorkbooks(reports);setSkipped(omitted);}
 })().catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{current=false};},[ctx.schoolId,ctx.loading,classId,term,session,selection]);
 async function downloadExcel(){if(!supabase||saving||!workbooks.length)return;setSaving(true);setSaveMessage('');try{const subjects=await supabase.from('schoolpro_subjects').select('id,name').eq('school_id',ctx.schoolId!);if(subjects.error)throw Error();const names=new Map((subjects.data||[]).map(s=>[s.id,s.name]));const book=buildClassResultsWorkbook({schoolName:ctx.schoolName||'SchoolPro',term,session,reports:workbooks,subjectNames:names});const saved=await saveSchoolFile(new Blob([await book.xlsx.writeBuffer()],{type:XLSX_MIME}),schoolFileName([ctx.schoolName,classId==='all'?'All Classes':students[0]?.class_name,term,session,selection?'Selected Results':'Class Results'],'xlsx'));setSaveMessage(saved?'Your Excel file has been saved.':'Saving was cancelled. Your reports are still available.');}catch{setSaveMessage('The Excel results could not be saved. Please try again.');}finally{setSaving(false)}}
 return <main className="min-h-screen bg-slate-100 p-4 print:bg-white print:p-0"><header className="mx-auto mb-4 flex max-w-5xl flex-wrap items-center justify-between gap-3 print:hidden"><h1 className="text-xl font-bold">Full class reports · {term} · {session}</h1><Button disabled={loading||!!error||!students.length||students.some(s=>ready[s.id]!==true)} onClick={()=>void printSchoolDocument({name:schoolFileName([ctx.schoolName,classId==='all'?'All Classes':students[0]?.class_name,term,session,'Full Results'],'pdf')})}>Print / Save PDF</Button><Button disabled={loading||saving||!!error||!workbooks.length} onClick={()=>void downloadExcel()}>{saving?'Saving…':'Download class results Excel'}</Button></header>{skipped>0&&<p role="status">{skipped} held result(s) were excluded. Review result access in your school settings.</p>}{saveMessage&&<p role="status">{saveMessage}</p>}{loading&&<p>Loading published reports…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!students.length&&<p>No published reports in this selection.</p>}<div className="mx-auto max-w-5xl">{students.map(s=><SchoolProReportCard key={s.id} embedded onReady={reportReady} selection={{student:s.id,term,session}}/>)}</div></main>;
}
