import {SchoolAccountForm} from '@/components/SchoolAccountForm';
import { useCallback, useEffect, useState } from "react";
import { RefreshCw, Search, Trash2 } from "lucide-react";
import { ModulePage } from "@/components/ModulePage";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { schoolSections, status } from "./schoolShared";
import { useSchoolProContext } from "@/hooks/useSchoolProContext";

type School={id:string;name:string;owner_id:string}; type Role="administrator"|"teacher"|"accountant";
type Member={id:string;user_id:string;role:Role|"proprietor";profile:{email:string;first_name:string|null;last_name:string|null}|null};
export function SchoolProStaff(){
 const {user,profile}=useAuth(); const ctx=useSchoolProContext(); const [schools,setSchools]=useState<School[]>([]); const [schoolId,setSchoolId]=useState(""); const [members,setMembers]=useState<Member[]>([]); const [search,setSearch]=useState(""); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
 const userName=profile?[profile.first_name,profile.last_name].filter(Boolean).join(" ")||profile.email:"School User";
 const loadSchools=useCallback(async()=>{if(!supabase||!user||ctx.loading)return;if(ctx.schoolId){setSchools([{id:ctx.schoolId,name:ctx.schoolName,owner_id:user.id}]);setSchoolId(ctx.schoolId);return;}setSchools([]);setSchoolId("");},[user,ctx.loading,ctx.schoolId,ctx.schoolName]);
 const loadMembers=useCallback(async()=>{if(!supabase||!schoolId)return;const {data,error}=await supabase.from("schoolpro_members").select("id,user_id,role,profile:profiles(email,first_name,last_name)").eq("school_id",schoolId).order("created_at");if(error)setError("Staff access could not be updated. Please try again.");else setMembers((data||[]) as unknown as Member[]);},[schoolId]);
 useEffect(()=>{void loadSchools();},[loadSchools]); useEffect(()=>{void loadMembers();},[loadMembers]);
 async function changeRole(member:Member,role:Role){if(!supabase)return;const {error}=await supabase.from("schoolpro_members").update({role}).eq("id",member.id);if(error)setError("Staff access could not be updated. Please try again.");else{setMessage("Staff role updated.");await loadMembers();}}
 async function remove(member:Member){if(!supabase||!window.confirm("Remove this staff member from the school?"))return;const {error}=await supabase.from("schoolpro_members").delete().eq("id",member.id);if(error)setError("Staff access could not be updated. Please try again.");else{setMessage("Staff access removed.");await loadMembers();}}
 const selected=schools.find(s=>s.id===schoolId); const ownerCount=selected?1:0; const visibleMembers=members.filter(m=>{const q=search.trim().toLowerCase();if(!q)return true;return [m.profile?.email,m.profile?.first_name,m.profile?.last_name,m.role].filter(Boolean).join(" ").toLowerCase().includes(q);});
 return <ModulePage product="schoolpro" sections={schoolSections} title="Staff & Access" description="Add school staff and control access by role. New staff choose their own password at first sign-in." userName={userName} userRole="School Administrator" primaryAction="Invite Staff" metrics={[{label:"Proprietors",value:String(ownerCount)},{label:"Administrators",value:String(members.filter(m=>m.role==="administrator").length)},{label:"Teachers",value:String(members.filter(m=>m.role==="teacher").length)},{label:"Accountants",value:String(members.filter(m=>m.role==="accountant").length)}]}>
  {(error||message)&&<div className={`rounded-xl border p-3 text-sm ${error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error||message}</div>}
  <div className="flex items-center justify-between gap-3"><select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="rounded-lg border border-border bg-white px-3 py-2 text-sm">{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button variant="secondary" size="sm" leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>void loadMembers()}>Refresh</Button></div>
  {!schoolId?<Card><p className="text-sm text-muted">Create a school workspace before inviting staff.</p></Card>:<div className="grid gap-5 lg:grid-cols-[380px_1fr]"><Card><h3 className="font-bold">Add a staff member</h3><SchoolAccountForm key={schoolId} schoolId={schoolId} onAdded={loadMembers}/></Card><Card padding="none" className="overflow-hidden"><div className="border-b p-5"><h3 className="font-bold">Active staff access</h3><p className="text-sm text-muted">Change a role or remove access at any time.</p><label className="mt-3 flex items-center gap-2 rounded-lg border bg-white px-3 py-2"><Search className="h-4 w-4 text-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff by name, email or role" className="w-full bg-transparent text-sm outline-none"/></label></div><div className="overflow-x-auto"><div className="school-table-scroll"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{["Staff member","Email","Role","Status",""].map(h=><th key={h} className="p-3 text-xs uppercase text-muted">{h}</th>)}</tr></thead><tbody>{visibleMembers.map(member=>{const name=[member.profile?.first_name,member.profile?.last_name].filter(Boolean).join(" ")||"Invited staff";return <tr key={member.id} className="border-t"><td className="p-3 font-semibold">{name}</td><td className="p-3">{member.profile?.email||"Invitation pending"}</td><td className="p-3"><select value={member.role} disabled={member.role==="proprietor"} onChange={e=>void changeRole(member,e.target.value as Role)} className="rounded-lg border bg-white p-2 text-xs"><option value="administrator">Administrator</option><option value="teacher">Teacher</option><option value="accountant">Accountant</option>{member.role==="proprietor"&&<option value="proprietor">Proprietor</option>}</select></td><td className="p-3">{status("Active")}</td><td className="p-3"><button disabled={member.role==="proprietor"} onClick={()=>void remove(member)} className="text-rose-600 disabled:opacity-30" aria-label="Remove access"><Trash2 className="h-4 w-4"/></button></td></tr>})}</tbody></table></div>{!members.length&&<p className="p-8 text-center text-sm text-muted">No staff members have been added yet.</p>}</div></Card></div>}
 </ModulePage>;
}
