import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Printer } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { Button } from "@/components/ui/Button";
import { supabase } from "@/lib/supabase";

type Component={key:string;label:string;maxScore:number};
type Row={id:string;assessment_scores:Record<string,number>;assessment_scheme_id:string|null;total_score:number;status:string;subject:{name:string}|null};
type RawRow=Omit<Row,"total_score"> & {total_score:number|string};
type Student={id:string;first_name:string;last_name:string;admission_number:string;class_name:string;school_id:string};
type School={name:string;address:string|null};
const grade=(score:number)=>score>=80?"A":score>=70?"B":score>=60?"C":score>=50?"D":score>=40?"E":"F";

export function SchoolProReportCard(){
 const [params]=useSearchParams(); const [student,setStudent]=useState<Student|null>(null); const [school,setSchool]=useState<School|null>(null); const [rows,setRows]=useState<Row[]>([]); const [components,setComponents]=useState<Component[]>([]); const [error,setError]=useState<string|null>(null); const [access,setAccess]=useState<{allowed:boolean;outstanding:number;reason:string|null}|null>(null);
 const term=params.get("term")||"First Term",session=params.get("session")||"2026/2027",studentId=params.get("student");
 // @ts-expect-error The RPC response type becomes available after the new database migration is generated.
 useEffect(()=>{async function load(){if(!supabase||!studentId)return;const {data:s,error:e}=await supabase.from("schoolpro_students").select("id,first_name,last_name,admission_number,class_name,school_id").eq("id",studentId).maybeSingle();if(e||!s){setError(e?.message||"Student not found");return;}setStudent(s as Student);const [schoolResult,resultResult,accessResult]=await Promise.all([supabase.from("schoolpro_schools").select("name,address").eq("id",s.school_id).maybeSingle(),supabase.from("schoolpro_results").select("id,assessment_scores,assessment_scheme_id,total_score,status,subject:schoolpro_subjects(name)").eq("student_id",studentId).eq("term",term).eq("session",session).order("created_at"),supabase.rpc("schoolpro_result_access",{target_student:studentId,target_term:term,target_session:session}).maybeSingle()]);if(schoolResult.error||resultResult.error||accessResult.error){setError((schoolResult.error||resultResult.error||accessResult.error)?.message||"Unable to load report");return;}setAccess(accessResult.data?{allowed:Boolean(accessResult.data.allowed),outstanding:Number(accessResult.data.outstanding),reason:accessResult.data.reason}:null);const rawRows=(resultResult.data||[]) as unknown as RawRow[];const resultRows=rawRows.map(r=>({...r,total_score:Number(r.total_score),assessment_scores:r.assessment_scores||{}}));setSchool(schoolResult.data as School|null);setRows(resultRows);const schemeId=resultRows[0]?.assessment_scheme_id;if(schemeId){const {data}=await supabase.from("schoolpro_assessment_schemes").select("components").eq("id",schemeId).maybeSingle();setComponents((data?.components||[]) as Component[]);}}void load();},[studentId,term,session]);
 const average=useMemo(()=>rows.length?rows.reduce((sum,r)=>sum+r.total_score,0)/rows.length:0,[rows]);
 if(student&&access?.allowed===false)return <PageShell product="schoolpro" showFooter={false}><div className="min-h-screen bg-surface p-4 md:p-8"><div className="mx-auto max-w-2xl rounded-2xl border border-amber-200 bg-amber-50 p-8 text-center shadow-float"><h1 className="text-2xl font-black text-amber-900">Report card access paused</h1><p className="mt-2 text-amber-800">{access.reason}</p><p className="mt-4 font-bold text-amber-900">Outstanding balance: {new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(access.outstanding)}</p><p className="mt-2 text-sm text-amber-700">Please contact the school bursary after payment.</p></div></div></PageShell>;
 return <PageShell product="schoolpro" showFooter={false}><div className="min-h-screen bg-surface p-4 md:p-8"><div className="mx-auto mb-4 flex max-w-6xl justify-end"><Button variant="secondary" leftIcon={<Printer className="h-4 w-4"/>} onClick={()=>window.print()}>Print Report</Button></div><article className="mx-auto max-w-6xl bg-white p-6 shadow-float md:p-10">{error&&<p className="text-rose-600">{error}</p>}{!studentId&&<p className="text-center text-muted">Open a result to view its report card.</p>}{student&&<><header className="border-b-4 border-purple-600 pb-5 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-purple-600 to-indigo-600 text-2xl font-black text-white">IH</div><h1 className="mt-3 text-2xl font-black text-navy-900">{school?.name||"IHLink SchoolPro"}</h1><p className="text-sm text-muted">{school?.address||"Nigeria"}</p><h2 className="mt-4 font-bold text-purple-700">{term.toUpperCase()} REPORT • {session} SESSION</h2></header><section className="my-6 grid grid-cols-1 gap-4 text-sm md:grid-cols-3"><div><b>Student:</b><br/>{student.first_name} {student.last_name}</div><div><b>Admission No:</b><br/>{student.admission_number}</div><div><b>Class:</b><br/>{student.class_name}</div></section><div className="overflow-x-auto"><table className="w-full border-collapse text-sm"><thead><tr className="bg-purple-700 text-white"><th className="border border-purple-500 p-3">Subject</th>{components.map(c=><th key={c.key} className="border border-purple-500 p-3">{c.label}<br/>/ {c.maxScore}</th>)}<th className="border border-purple-500 p-3">Total</th><th className="border border-purple-500 p-3">Grade</th><th className="border border-purple-500 p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="border p-3 font-semibold">{r.subject?.name||"Subject"}</td>{components.map(c=><td key={c.key} className="border p-3">{r.assessment_scores[c.key]??0}</td>)}<td className="border p-3 font-bold">{r.total_score}</td><td className="border p-3 font-bold">{grade(r.total_score)}</td><td className="border p-3 capitalize">{r.status}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="py-8 text-center text-sm text-muted">No result records for this term and session.</p>}<footer className="mt-8 flex justify-between border-t pt-5 text-xs text-muted"><span>Average: {average.toFixed(1)}%</span><span>Generated by IHLink SchoolPro</span></footer></>}</article></div></PageShell>;
}
