import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Download, ReceiptText } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';

type Receipt = { id:string; school_id:string; invoice_id:string; student_id:string; amount:number; method:string; reference:string; notes:string|null; paid_at:string };
type Student = { first_name:string; last_name:string; admission_number:string; class_name:string };
type Invoice = { title:string; term:string; session:string; amount_due:number; amount_paid:number };
type School = { name:string; address:string|null; phone:string|null; email:string|null };
const money=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',minimumFractionDigits:2}).format(value);

export function SchoolProReceipt(){
 const {receiptId}=useParams(); const {profile}=useAuth(); const [receipt,setReceipt]=useState<Receipt|null>(null),[student,setStudent]=useState<Student|null>(null),[invoice,setInvoice]=useState<Invoice|null>(null),[school,setSchool]=useState<School|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!supabase||!receiptId)return;setLoading(true);setError(null);const p=await supabase.from('schoolpro_fee_payments').select('id,school_id,invoice_id,student_id,amount,method,reference,notes,paid_at').eq('id',receiptId).maybeSingle();if(p.error||!p.data){setError(p.error?.message||'Receipt not found or you do not have permission to view it.');setLoading(false);return;}const row={...p.data,amount:Number(p.data.amount)} as Receipt;setReceipt(row);const [s,i,sc]=await Promise.all([supabase.from('schoolpro_students').select('first_name,last_name,admission_number,class_name').eq('id',row.student_id).maybeSingle(),supabase.from('schoolpro_invoices').select('title,term,session,amount_due,amount_paid').eq('id',row.invoice_id).maybeSingle(),supabase.from('schoolpro_schools').select('name,address,phone,email').eq('id',row.school_id).maybeSingle()]);const issue=s.error||i.error||sc.error;if(issue)setError(issue.message);setStudent(s.data as Student|null);setInvoice(i.data?{...i.data,amount_due:Number(i.data.amount_due),amount_paid:Number(i.data.amount_paid)} as Invoice:null);setSchool(sc.data as School|null);setLoading(false);},[receiptId]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <main className="min-h-screen bg-slate-50 p-6"><p className="mx-auto max-w-3xl text-sm text-slate-600">Loading verified receipt…</p></main>;
 if(error||!receipt)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-3xl rounded-2xl border border-rose-200 bg-white p-8"><h1 className="text-xl font-bold text-slate-950">Receipt unavailable</h1><p className="mt-2 text-sm text-rose-700">{error}</p><Link className="mt-5 inline-block" to="/schoolpro/parent-dashboard"><Button variant="secondary" leftIcon={<ArrowLeft className="h-4 w-4"/>}>Back to dashboard</Button></Link></div></main>;
 return <main className="min-h-screen bg-slate-100 px-4 py-8 print:bg-white print:p-0"><div className="mx-auto max-w-3xl"><div className="mb-4 flex items-center justify-between print:hidden"><Link to="/schoolpro/parent-dashboard"><Button variant="secondary" leftIcon={<ArrowLeft className="h-4 w-4"/>}>Back</Button></Link><Button leftIcon={<Download className="h-4 w-4"/>} onClick={()=>window.print()}>Print / Save PDF</Button></div><article className="print-document rounded-3xl border border-slate-200 bg-white p-7 shadow-sm print:border-0 print:shadow-none md:p-10"><header className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 sm:flex-row sm:items-start"><div className="flex gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-purple-100 text-purple-700"><ReceiptText className="h-6 w-6"/></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-purple-700">IHLink SchoolPro</p><h1 className="mt-1 text-2xl font-extrabold text-slate-950">Official payment receipt</h1></div></div><div className="sm:text-right"><p className="font-bold text-slate-950">{school?.name||'School'}</p><p className="mt-1 text-xs leading-5 text-slate-500">{school?.address}<br/>{school?.phone} {school?.email&&`· ${school.email}`}</p></div></header><section className="grid gap-6 border-b border-slate-200 py-7 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Received from</p><p className="mt-2 text-lg font-bold text-slate-950">{student?.first_name} {student?.last_name}</p><p className="text-sm text-slate-600">{student?.admission_number} · {student?.class_name}</p></div><div className="sm:text-right"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Amount paid</p><p className="mt-2 text-3xl font-extrabold text-emerald-700">{money(receipt.amount)}</p><p className="text-sm font-semibold text-emerald-700">Payment successful</p></div></section><dl className="grid gap-x-8 gap-y-5 py-7 sm:grid-cols-2">{[['Receipt reference',receipt.reference],['Payment date',new Date(receipt.paid_at).toLocaleString('en-NG',{dateStyle:'long',timeStyle:'short'})],['Payment method',receipt.method.toUpperCase()],['Invoice',invoice?.title||'School fee'],['Academic period',invoice?`${invoice.term} · ${invoice.session}`:'—'],['Invoice balance',invoice?money(Math.max(0,invoice.amount_due-invoice.amount_paid)):'—']].map(([label,value])=><div key={label}><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm font-semibold text-slate-900">{value}</dd></div>)}</dl><footer className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-600"><p>This receipt confirms a payment recorded in IHLink SchoolPro. Keep the reference for reconciliation.</p><p className="mt-3 text-xs text-slate-500">Generated for {profile?.email||'the account holder'} on {new Date().toLocaleString('en-NG')}.</p></footer></article></div></main>;
}
