import {useEffect,useMemo,useState} from 'react';import {ModulePage} from '@/components/ModulePage';import {schoolSections,status} from './schoolShared';import {supabase} from '@/lib/supabase';import {useSchoolProContext} from '@/hooks/useSchoolProContext';import {useAuth} from '@/context/AuthContext';import {Card} from '@/components/ui/Card';import {Button} from '@/components/ui/Button';import {Search} from 'lucide-react';
const defs:Record<string,{title:string;description:string;action:string;table:string;fields:{key:string;label:string;type?:string}[]}>={
admissions:{title:'Admissions',description:'Manage applications and enrolment decisions.',action:'New Application',table:'schoolpro_admissions',fields:[{key:'applicant_name',label:'Applicant name'},{key:'guardian_name',label:'Guardian name'},{key:'guardian_contact',label:'Guardian contact'},{key:'class_applied',label:'Class applied'}]},
timetable:{title:'Timetable',description:'Build and maintain class timetable entries.',action:'Add Timetable Entry',table:'schoolpro_timetable_entries',fields:[{key:'weekday',label:'Weekday (1-7)',type:'number'},{key:'starts_at',label:'Start time',type:'time'},{key:'ends_at',label:'End time',type:'time'},{key:'room',label:'Room'}]},
assignments:{title:'Assignments',description:'Create and track classroom assignments.',action:'New Assignment',table:'schoolpro_assignments',fields:[{key:'title',label:'Title'},{key:'instructions',label:'Instructions'},{key:'due_at',label:'Due date',type:'datetime-local'},{key:'max_score',label:'Maximum score',type:'number'}]},
cbt:{title:'Computer-Based Tests',description:'Create timed CBT assessments.',action:'Create Test',table:'schoolpro_cbt_tests',fields:[{key:'title',label:'Test title'},{key:'duration_minutes',label:'Duration minutes',type:'number'},{key:'total_marks',label:'Total marks',type:'number'}]},
library:{title:'Library',description:'Manage library catalogue and availability.',action:'Add Book',table:'schoolpro_library_books',fields:[{key:'title',label:'Book title'},{key:'author',label:'Author'},{key:'isbn',label:'ISBN'},{key:'copies',label:'Copies',type:'number'}]},
transport:{title:'Transportation',description:'Manage routes, vehicles and drivers.',action:'Add Route',table:'schoolpro_transport_routes',fields:[{key:'name',label:'Route name'},{key:'vehicle',label:'Vehicle'},{key:'driver_name',label:'Driver'},{key:'driver_phone',label:'Driver phone'}]},
hostel:{title:'Hostel',description:'Manage hostels, rooms and capacity.',action:'Add Room',table:'schoolpro_hostel_rooms',fields:[{key:'hostel_name',label:'Hostel'},{key:'room',label:'Room'},{key:'capacity',label:'Capacity',type:'number'},{key:'fee',label:'Fee',type:'number'}]},
inventory:{title:'Inventory & Assets',description:'Track assets and stock.',action:'Add Asset',table:'schoolpro_inventory_assets',fields:[{key:'name',label:'Asset name'},{key:'category',label:'Category'},{key:'quantity',label:'Quantity',type:'number'},{key:'location',label:'Location'}]},
discipline:{title:'Discipline',description:'Track incidents and follow-up actions.',action:'Log Incident',table:'schoolpro_discipline_records',fields:[{key:'incident',label:'Incident'},{key:'action_taken',label:'Action taken'}]},
announcements:{title:'Communication Centre',description:'Publish targeted school announcements.',action:'New Announcement',table:'schoolpro_announcements',fields:[{key:'title',label:'Title'},{key:'body',label:'Message'},{key:'audience',label:'Audience'}]},
};

function AssignmentSubmissions({assignment}:{assignment:any}){const[submissions,setSubmissions]=useState<any[]>([]),[scores,setScores]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[targets,setTargets]=useState<any[]>([]);async function load(){if(!supabase)return;const r=await supabase.from('schoolpro_assignment_submissions').select('id,submission_text,file_url,submitted_at,status,score,feedback,student:schoolpro_students(first_name,last_name,admission_number)').eq('assignment_id',assignment.id).order('submitted_at',{ascending:false});setSubmissions(r.data||[]);if(r.error)setNotice(r.error.message)}useEffect(()=>{void load()},[assignment.id]);async function grade(id:string){if(!supabase)return;const value=Number(scores[id]);if(!Number.isFinite(value)){setNotice('Enter a valid score.');return}const r=await supabase.rpc('grade_schoolpro_assignment_submission',{p_submission:id,p_score:value,p_feedback:feedback[id]||null});setNotice(r.error?.message||'Submission graded.');if(!r.error)await load()}return <div className="mt-3 space-y-3"><p className="text-xs font-semibold text-muted">Submissions: {submissions.length} · Maximum score: {assignment.max_score??100}</p>{submissions.map((s:any)=><div key={s.id} className="rounded-lg border p-3 text-sm space-y-2"><p className="font-semibold">{[s.student?.first_name,s.student?.last_name].filter(Boolean).join(' ')||'Student'} <span className="font-normal text-muted">{s.student?.admission_number||''}</span></p><p>{s.submission_text||'No text response.'}</p>{s.file_url&&<a className="underline" href={s.file_url} target="_blank" rel="noreferrer">Open submitted file/link</a>}<p className="text-xs text-muted">Submitted {new Date(s.submitted_at).toLocaleString()} · {s.status}</p><div className="grid gap-2 md:grid-cols-[140px_1fr_auto]"><input type="number" min="0" max={assignment.max_score??100} placeholder={s.score==null?'Score':String(s.score)} value={scores[s.id]??''} onChange={e=>setScores(x=>({...x,[s.id]:e.target.value}))} className="rounded-lg border p-2"/><input placeholder={s.feedback||'Feedback'} value={feedback[s.id]??''} onChange={e=>setFeedback(x=>({...x,[s.id]:e.target.value}))} className="rounded-lg border p-2"/><Button size="sm" onClick={()=>void grade(s.id)}>Grade</Button></div>{s.score!=null&&<p className="text-xs font-semibold">Current grade: {s.score}/{assignment.max_score??100}{s.feedback?' · '+s.feedback:''}</p>}</div>)}{!submissions.length&&<p className="text-sm text-muted">No submissions yet.</p>}{notice&&<p className="text-xs text-muted">{notice}</p>}</div>}
export function SchoolProModulePage({module}:{module:string}){const d=defs[module];const ctx=useSchoolProContext();const {profile,user}=useAuth();const [rows,setRows]=useState<any[]>([]),[query,setQuery]=useState(''),[form,setForm]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
async function load(){if(!d||!supabase||!ctx.schoolId)return;const r=await supabase.from(d.table).select('*').eq('school_id',ctx.schoolId).order('created_at',{ascending:false});setRows(r.data||[]);if(r.error)setNotice(r.error.message)}
useEffect(()=>{void load();if(module==='assignments'&&supabase&&ctx.schoolId&&user){void(async()=>{const m=await supabase.from('schoolpro_members').select('id,role').eq('school_id',ctx.schoolId).eq('user_id',user.id).maybeSingle();if(!m.data)return;let q:any=supabase.from('schoolpro_subject_assignments').select('class_id,subject_id,session,schoolpro_classes(name,arm),schoolpro_subjects(name)').eq('school_id',ctx.schoolId);if(['teacher','class_teacher'].includes(m.data.role))q=q.eq('teacher_member_id',m.data.id);const r=await q;setTargets(r.data||[])})()}},[ctx.schoolId,module,user?.id]);
const filtered=useMemo(()=>rows.filter(r=>!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
async function save(){if(!supabase||!ctx.schoolId||!d)return;const required:Record<string,string[]>={timetable:['weekday','starts_at','ends_at'],assignments:['title','class_id','subject_id','session'],announcements:['title','body','audience']};const missing=(required[module]||[]).filter(k=>!String(form[k]||'').trim());if(missing.length){setNotice('Required: '+missing.map(k=>k.replaceAll('_',' ')).join(', ')+'.');return;}if(module==='timetable'){const day=Number(form.weekday);if(day<1||day>7){setNotice('Weekday must be between 1 and 7.');return;}}const payload:any={school_id:ctx.schoolId};if(module==='assignments'){payload.class_id=form.class_id;payload.subject_id=form.subject_id;payload.session=form.session;}for(const f of d.fields){const v=form[f.key];if(v!=='')payload[f.key]=f.type==='number'?Number(v):v;}if(['assignments','cbt','discipline'].includes(module))payload.created_by=user?.id;if(module==='announcements')payload.created_by=user?.id;const r=await supabase.from(d.table).insert(payload);setNotice(r.error?.message||'Saved successfully.');if(!r.error){setForm({});await load();}}
if(!d)return <ModulePage product="schoolpro" sections={schoolSections} title="SchoolPro Module" description="This module is being configured." userName={ctx.schoolName} userRole={ctx.role}/>;
if(ctx.loading)return <div className="min-h-screen grid place-items-center">Loading…</div>;if(!ctx.schoolId&&profile?.role!=='super_admin')return <ModulePage product="schoolpro" sections={schoolSections} title={d.title} description={d.description} userName="SchoolPro" userRole="No school access"><Card>School access required.</Card></ModulePage>;
return <ModulePage product="schoolpro" sections={schoolSections} title={d.title} description={d.description} userName={ctx.schoolName} userRole={ctx.role} metrics={[{label:'Records',value:String(rows.length)},{label:'Visible',value:String(filtered.length)},{label:'Data',value:'Live database'},{label:'Access',value:ctx.role}]}>
<Card><h3 className="font-bold">{d.action}</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{module==='assignments'&&<select value={(form.class_id||'')+'|'+(form.subject_id||'')+'|'+(form.session||'')} onChange={e=>{const[class_id,subject_id,session]=e.target.value.split('|');setForm(x=>({...x,class_id,subject_id,session}))}} className="rounded-lg border p-2.5 text-sm"><option value="|">Select assigned class & subject</option>{targets.map((t:any)=><option key={t.class_id+'|'+t.subject_id+'|'+t.session} value={t.class_id+'|'+t.subject_id+'|'+t.session}>{[t.schoolpro_classes?.name,t.schoolpro_classes?.arm].filter(Boolean).join(' ')} · {t.schoolpro_subjects?.name} · {t.session}</option>)}</select>}{d.fields.map(f=><input key={f.key} type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm(x=>({...x,[f.key]:e.target.value}))} placeholder={f.label} className="rounded-lg border p-2.5 text-sm"/>)}<Button onClick={()=>void save()}>Save</Button>{notice&&<p className="self-center text-sm text-muted">{notice}</p>}</div></Card>
<Card className="mt-5"><div className="relative mb-4"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Search "+d.title.toLowerCase()+"…"} className="w-full rounded-xl border py-2.5 pl-10 pr-3 text-sm"/></div><div className="max-h-[60vh] overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="sticky-table-header"><tr>{d.fields.map(f=><th key={f.key} className="px-3 py-3 text-left">{f.label}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t">{d.fields.map(f=><td key={f.key} className="px-3 py-3">{String(r[f.key]??'—')}</td>)}</tr>)}</tbody></table>{!filtered.length&&<p className="p-8 text-center text-sm text-muted">No matching records.</p>}</div></Card>{module==='assignments'&&<div className="mt-5 grid gap-4">{filtered.map(a=><Card key={'sub-'+a.id}><h3 className="font-bold">{a.title}</h3><p className="text-sm text-muted">{a.instructions||'No instructions'} · Due {a.due_at?new Date(a.due_at).toLocaleString():'No deadline'}</p><AssignmentSubmissions assignment={a}/></Card>)}</div>}</ModulePage>}