import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2 } from 'lucide-react';
import { deployedPlatform } from '@/lib/platformUrls';

type Brand={name:string;logo:string;eyebrow:string;headline:string;points:string[];aside:string;accent:string};
const brands:Record<string,Brand>={
 corporate:{name:'IHLink Co. Ltd.',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Corporate',headline:'One company. Multiple specialist platforms.',points:['Discover IHLink products and services','Corporate account and support','Choose the service you want to join'],aside:'bg-navy-900',accent:'text-sky-300'},
 datasub:{name:'IHLink DataSub',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink DataSub',headline:'Smart digital services. Simple, fast and dependable.',points:['Buy data, airtime and digital services','Manage your DataSub wallet and transactions','Smart Earner, Reseller and API access'],aside:'bg-emerald-950',accent:'text-emerald-300'},
 schoolpro:{name:'IHLink SchoolPro',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink SchoolPro',headline:'Modern school operations, academics and results in one place.',points:['School-specific account and workspace','Results, fees, attendance and communication','Role-based access for school users'],aside:'bg-purple-950',accent:'text-purple-300'},
 consult:{name:'IHLink Consult',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Consult',headline:'Technology consulting built around your project.',points:['Dedicated client account','Projects, quotes and consultations','Secure client support and delivery'],aside:'bg-orange-950',accent:'text-orange-300'},
 host:{name:'IHLink Hosting & Domains',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Hosting & Domains',headline:'Domains, hosting and infrastructure for your online presence.',points:['Dedicated hosting customer account','Domains and hosting services','Support for your hosted services'],aside:'bg-cyan-950',accent:'text-cyan-300'},
 engineering:{name:'IHLink Engineering',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Engineering',headline:'Engineering, automation and intelligent systems.',points:['Dedicated engineering client account','Control, robotics and instrumentation','Project support and delivery'],aside:'bg-amber-950',accent:'text-amber-300'},
 print:{name:'IHLink Print & Branding',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Print & Branding',headline:'Professional print, identity and branding services.',points:['Dedicated customer account','Print and branding orders','Project history and support'],aside:'bg-rose-950',accent:'text-rose-300'},
 fabrication:{name:'IHLink 3D Fabrication Lab',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink 3D Fabrication Lab',headline:'From digital model to physical prototype.',points:['Dedicated fabrication account','3D printing and prototyping','Track fabrication requests'],aside:'bg-slate-950',accent:'text-slate-300'},
 compute:{name:'IHLink AI & Compute',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink AI & Compute',headline:'AI and compute services for modern workloads.',points:['Dedicated AI & Compute account','Compute services and solutions','Account-scoped support'],aside:'bg-indigo-950',accent:'text-indigo-300'},
 academy:{name:'IHLink Academy',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Academy',headline:'Practical technology learning for real-world skills.',points:['Dedicated learner account','Courses and learning services','Progress and learner support'],aside:'bg-blue-950',accent:'text-blue-300'},
 digital_business:{name:'IHLink Digital Business Centre',logo:'/brand/ihlink-icon.png',eyebrow:'IHLink Digital Business Centre',headline:'Digital services that help people and businesses get things done.',points:['Dedicated customer account','Business and digital services','Requests, records and support'],aside:'bg-teal-950',accent:'text-teal-300'}
};
export function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){
 const brand=brands[deployedPlatform]||brands.corporate;
 return <div className="min-h-screen grid lg:grid-cols-[45%_55%] bg-white"><aside className={`${brand.aside} text-white p-8 lg:p-12 flex flex-col justify-between relative overflow-hidden min-h-[320px] lg:min-h-screen`}><div className="absolute -left-32 bottom-16 w-96 h-96 rounded-full bg-white/10 blur-2xl"/><Link to="/" className="relative inline-flex items-center gap-3"><span className="h-16 w-16 rounded-2xl bg-white p-2 shadow-lg grid place-items-center"><img src={brand.logo} alt={brand.name} className="h-full w-full object-contain"/></span><span><strong className="block text-xl">{brand.name}</strong><small className="text-white/60">by IHLink Co. Ltd.</small></span></Link><div className="relative"><p className={`uppercase tracking-[.2em] text-xs font-bold ${brand.accent}`}>{brand.eyebrow}</p><h2 className="text-4xl font-black mt-4">{brand.headline}</h2><div className="space-y-4 mt-8">{brand.points.map(x=><p className="flex gap-3 text-white/80" key={x}><CheckCircle2 className="text-emerald-400 w-5 h-5 shrink-0"/>{x}</p>)}</div></div><p className="relative text-xs text-white/50">© 2026 IHLink Co. Ltd. · {brand.name}</p></aside><main className="p-6 sm:p-12 grid place-items-center"><div className="w-full max-w-md"><div className="lg:hidden mb-6 flex items-center gap-2"><img src={brand.logo} className="h-10 w-10 object-contain" alt=""/><strong>{brand.name}</strong></div><h1 className="text-3xl font-black text-navy-900">{title}</h1><p className="text-muted mt-2 mb-8">{subtitle}</p>{children}</div></main></div>
}