import {useState} from 'react';
import {downloadSchoolFile,XLSX_MIME} from '@/lib/schoolDownloads';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
const base='/templates/ihlink-academy/';
export const sampleTemplateUrl=(name:string)=>base+name;
export function SharedTemplateGallery({kind,onUse,busy=false}:{kind:'result'|'document'|'invoice';onUse?:(key:string)=>void;busy?:boolean}){
 const [notice,setNotice]=useState(''),[downloading,setDownloading]=useState(false);
 async function download(name:string){setDownloading(true);setNotice('Preparing download…');try{const saved=await downloadSchoolFile(base+name,name,name.endsWith('.xlsx')?XLSX_MIME:undefined);setNotice(saved?'File saved.':'Save cancelled.');}catch{setNotice('The file could not be downloaded. Please try again.');}finally{setDownloading(false);}}
 const names=kind==='result'?['Nursery','Primary','Junior-Secondary','Senior-Secondary']:kind==='document'?['Certificate','Document']:['Invoice'];
 return <Card><h3 className="font-bold">IHLink Academy sample designs</h3><p className="mt-2 text-sm text-muted">Preview designs for your school. Save your own copy, personalise it, or replace it with your school’s template.</p>{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2">{names.map(name=><div key={name} className="min-w-0 rounded-xl border p-3"><h4 className="font-semibold">{name.replaceAll('-',' ')}</h4><span className="text-xs text-muted">Sample preview</span><img loading="lazy" src={base+name+'-Preview.png'} alt={name+' sample design'} className="mt-2 h-56 w-full rounded-lg bg-slate-50 object-contain"/><details className="mt-2"><summary className="cursor-pointer text-sm font-semibold">View complete preview</summary><img loading="lazy" src={base+name+'-Preview.png'} alt={name+' complete sample preview'} className="mt-2 w-full object-contain"/></details><div className="mt-3 flex flex-wrap gap-2">{onUse&&<Button size="sm" disabled={busy} onClick={()=>onUse(name)}>Use a copy</Button>}<Button type="button" size="sm" variant="secondary" disabled={downloading} onClick={()=>void download(kind==='result'?'IHLink-Academy-'+name+'-Result.xlsx':name+'-Template.pdf')}>Download template</Button>{kind!=='result'&&<Button type="button" size="sm" variant="secondary" disabled={downloading} onClick={()=>void download(name+'-Preview.pdf')}>Download preview</Button>}</div></div>)}</div>{kind!=='invoice'&&<Button type="button" className="mt-3" size="sm" variant="secondary" disabled={downloading} onClick={()=>void download(kind==='result'?'Result-Mappings.json':'Document-Mappings.json')}>Download field mappings</Button>}</Card>;
}
