create or replace function private.schoolpro_module_allowed(target_school uuid, required_permission text) returns boolean language sql stable security invoker set search_path='' as $$
select case
when auth.uid() is null or not exists(select 1 from public.profiles p where p.id=auth.uid() and p.status::text='active') then false
when exists(select 1 from public.schoolpro_schools s where s.id=target_school and s.owner_id=auth.uid()) or exists(select 1 from public.schoolpro_members m where m.school_id=target_school and m.user_id=auth.uid()) or private.is_admin()
then required_permission=any(public.schoolpro_user_permissions(target_school))
else true end;
$$;
revoke all on function private.schoolpro_module_allowed(uuid,text) from public,anon;
grant execute on function private.schoolpro_module_allowed(uuid,text) to authenticated;
create policy schoolpro_module_permission on public.schoolpro_results as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'results')) with check (private.schoolpro_module_allowed(school_id,'results'));
create policy schoolpro_module_permission on public.schoolpro_result_templates as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'results')) with check (private.schoolpro_module_allowed(school_id,'results'));
create policy schoolpro_module_permission on public.schoolpro_result_approvals as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'results')) with check (private.schoolpro_module_allowed(school_id,'results'));
create policy schoolpro_module_permission on public.schoolpro_result_access_pins as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'results')) with check (private.schoolpro_module_allowed(school_id,'results'));
create policy schoolpro_module_permission on public.schoolpro_attendance as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'attendance')) with check (private.schoolpro_module_allowed(school_id,'attendance'));
create policy schoolpro_module_permission on public.schoolpro_assignments as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'assignments')) with check (private.schoolpro_module_allowed(school_id,'assignments'));
create policy schoolpro_module_permission on public.schoolpro_timetable_entries as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'timetable')) with check (private.schoolpro_module_allowed(school_id,'timetable'));
create policy schoolpro_module_permission on public.schoolpro_question_bank as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'cbt')) with check (private.schoolpro_module_allowed(school_id,'cbt'));
create policy schoolpro_module_permission on public.schoolpro_cbt_tests as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'cbt')) with check (private.schoolpro_module_allowed(school_id,'cbt'));
create policy schoolpro_module_permission on public.schoolpro_cbt_eligibility as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'cbt')) with check (private.schoolpro_module_allowed(school_id,'cbt'));
create policy schoolpro_module_permission on public.schoolpro_library_books as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'library')) with check (private.schoolpro_module_allowed(school_id,'library'));
create policy schoolpro_module_permission on public.schoolpro_library_loans as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'library')) with check (private.schoolpro_module_allowed(school_id,'library'));
create policy schoolpro_module_permission on public.schoolpro_transport_routes as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'transport')) with check (private.schoolpro_module_allowed(school_id,'transport'));
create policy schoolpro_module_permission on public.schoolpro_student_transport as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'transport')) with check (private.schoolpro_module_allowed(school_id,'transport'));
create policy schoolpro_module_permission on public.schoolpro_hostel_rooms as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'hostel')) with check (private.schoolpro_module_allowed(school_id,'hostel'));
create policy schoolpro_module_permission on public.schoolpro_hostel_allocations as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'hostel')) with check (private.schoolpro_module_allowed(school_id,'hostel'));
create policy schoolpro_module_permission on public.schoolpro_inventory_assets as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'inventory')) with check (private.schoolpro_module_allowed(school_id,'inventory'));
create policy schoolpro_module_permission on public.schoolpro_payroll_records as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'payroll')) with check (private.schoolpro_module_allowed(school_id,'payroll'));
create policy schoolpro_module_permission on public.schoolpro_discipline_records as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'discipline')) with check (private.schoolpro_module_allowed(school_id,'discipline'));
create policy schoolpro_module_permission on public.schoolpro_calendar_events as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'calendar')) with check (private.schoolpro_module_allowed(school_id,'calendar'));
create policy schoolpro_module_permission on public.schoolpro_lesson_notes as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'lesson-notes')) with check (private.schoolpro_module_allowed(school_id,'lesson-notes'));
create policy schoolpro_module_permission on public.schoolpro_leave_requests as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'leave')) with check (private.schoolpro_module_allowed(school_id,'leave'));
create policy schoolpro_module_permission on public.schoolpro_promotions as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'promotions')) with check (private.schoolpro_module_allowed(school_id,'promotions'));
create policy schoolpro_module_permission on public.schoolpro_health_records as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'medical')) with check (private.schoolpro_module_allowed(school_id,'medical'));
create policy schoolpro_module_permission on public.schoolpro_academic_documents as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'documents')) with check (private.schoolpro_module_allowed(school_id,'documents'));
create policy schoolpro_module_permission on public.schoolpro_document_templates as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'documents')) with check (private.schoolpro_module_allowed(school_id,'documents'));
create policy schoolpro_module_permission on public.schoolpro_document_issues as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'documents')) with check (private.schoolpro_module_allowed(school_id,'documents'));
create policy schoolpro_module_permission on public.schoolpro_announcements as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'announcements')) with check (private.schoolpro_module_allowed(school_id,'announcements'));
create policy schoolpro_module_permission on public.schoolpro_admissions as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'admissions')) with check (private.schoolpro_module_allowed(school_id,'admissions'));
create policy schoolpro_module_permission on public.schoolpro_branding as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'branding')) with check (private.schoolpro_module_allowed(school_id,'branding'));
create policy schoolpro_module_permission on public.schoolpro_site_content as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'branding')) with check (private.schoolpro_module_allowed(school_id,'branding'));
create policy schoolpro_module_permission on public.schoolpro_site_gallery as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'branding')) with check (private.schoolpro_module_allowed(school_id,'branding'));
create policy schoolpro_module_permission on public.schoolpro_site_news as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'branding')) with check (private.schoolpro_module_allowed(school_id,'branding'));
create policy schoolpro_module_permission on public.schoolpro_site_settings as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'branding')) with check (private.schoolpro_module_allowed(school_id,'branding'));
create policy schoolpro_module_permission on public.schoolpro_finance_settings as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_fee_structures as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_invoices as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_fee_payments as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_fee_records as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_payment_intents as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_invoice_templates as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_fee_exceptions as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_bank_accounts as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_payment_proofs as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_payment_allocations as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_charge_categories as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));
create policy schoolpro_module_permission on public.schoolpro_payment_submissions as restrictive for all to authenticated using (private.schoolpro_module_allowed(school_id,'finance')) with check (private.schoolpro_module_allowed(school_id,'finance'));

