import {useEffect,useState} from 'react';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
type RequestRow={id:string;status:string;requested_at:string;reason:string|null};
export function AccountClosureControl(){
 const {user}=useAuth();const [customer,setCustomer]=useState(false);
 useEffect(()=>{let active=true;setCustomer(false);if(supabase&&user)void supabase.from('profiles').select('role').eq('id',user.id).maybeSingle().then(({data})=>{if(active)setCustomer(data?.role==='customer')});return()=>{active=false}},[user?.id]);const [open,setOpen]=useState(false),[request,setRequest]=useState<RequestRow|null>(null),[reason,setReason]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 useEffect(()=>{let active=true;setRequest(null);setNote('');if(!open||!supabase||!user)return;setLoading(true);
 void supabase.from('account_deletion_requests').select('id,status,requested_at,reason').eq('user_id',user.id).order('requested_at',{ascending:false}).limit(1).maybeSingle().then(({data,error})=>{if(active){setRequest(data as RequestRow|null);setNote(error?.message||'');setLoading(false)}});
 return()=>{active=false};
 },[open,user?.id]);
 if(!user||!customer)return null;
 async function act(cancel=false){if(!supabase||busy)return;setBusy(true);setNote('');try{
 const result=cancel?await supabase.rpc('cancel_account_deletion'):await supabase.rpc('request_account_deletion',{p_reason:reason.trim()||null});
 if(result.error)throw result.error;const row=Array.isArray(result.data)?result.data[0]:result.data;
 if(!row?.id)throw new Error('The account request was not recorded.');
 setRequest(row as RequestRow);setNote(cancel?'Deletion request cancelled.':'Deletion request recorded for Super Admin review. Your account has not yet been deleted.');
 }catch(error){setNote((error as {message?:string})?.message||'Unable to record this request.')}finally{setBusy(false)}}
 return <div className="print:hidden"><button type="button" onClick={()=>setOpen(true)} className="fixed bottom-4 right-4 z-40 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-900 shadow">Account deletion</button>{open&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-label="Account deletion" className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-6 text-slate-900 shadow-xl"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">Close your IHLink account</h2><button type="button" disabled={busy} onClick={()=>setOpen(false)} className="rounded-lg border px-3 py-2">Close</button></div><p className="mt-3 text-sm">Your IHLink identity is shared across services. This request goes to the Super Admin review queue. Approval revokes access across the ecosystem; final deletion follows review and retains financial and audit references.</p>{loading?<p className="mt-4">Loading request status…</p>:request?.status==='pending'?<div className="mt-4"><p>Request {request.id} is pending review.</p><button type="button" disabled={busy} onClick={()=>void act(true)} className="mt-3 rounded-lg border px-4 py-2">{busy?'Saving…':'Cancel deletion request'}</button></div>:request?.status==='approved'||request?.status==='completed'?<p className="mt-4">Request status: {request.status}.</p>:<div className="mt-4"><label className="block text-sm font-bold">Reason (optional)<textarea maxLength={1000} rows={3} className="mt-2 w-full rounded-lg border p-3" value={reason} onChange={event=>setReason(event.target.value)}/></label><button type="button" disabled={busy||loading} onClick={()=>void act()} className="mt-3 rounded-lg bg-red-700 px-4 py-2 font-bold text-white">{busy?'Submitting…':'Request account deletion'}</button>{request&&<p className="mt-3 text-sm">Previous request: {request.status}.</p>}</div>}{note&&<p role="status" className="mt-4 rounded-lg border p-3 text-sm">{note}</p>}</section></div>}</div>;
}
