import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
import {InvoiceRevisionInbox} from '@/components/InvoiceRevisionInbox';
type Row=Record<string,any>;
const money=(n:unknown)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(n)||0);
const payable=['issued','unpaid','part_paid','overdue','awaiting_payment'];
const tables:Record<string,string>={consult:'consult_invoices',engineering:'engineering_invoices',print:'print_invoices',host:'host_invoices',fabrication:'business_invoices',compute:'business_invoices',academy:'business_invoices',digital_business:'business_invoices',business_centre:'business_invoices'};
export function BankTransferPayments({platform,instructions}:{platform:string;instructions?:Row[]}){
 const {user}=useAuth();const scope=useRef('');scope.current=`${user?.id}:${platform}`;const loadVersion=useRef(0);const [banks,setBanks]=useState<Row[]>([]),[invoices,setInvoices]=useState<Row[]>([]),[proofs,setProofs]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Row|null>(null),[file,setFile]=useState<File|null>(null),[search,setSearch]=useState('');
 const [form,setForm]=useState({bank:'',sender:'',senderBank:'',reference:'',date:''});
 async function load(){const version=++loadVersion.current,ownerScope=scope.current;const current=()=>version===loadVersion.current&&ownerScope===scope.current;if(!supabase||!user){setError('Sign in to view your invoices and payment proofs.');setLoading(false);return;}setLoading(true);try{
  const [b,p]=await Promise.all([supabase.from('ihlink_bank_accounts').select('id,bank_name,account_name,account_number').eq('is_active',true).order('is_default',{ascending:false}),supabase.from('direct_transfer_submissions').select('id,invoice_id,source_reference,bank_account_id,amount,status,customer_reference,created_at').eq('user_id',user.id).eq('platform_code',platform).order('created_at',{ascending:false})]);if(!current())return;if(b.error||p.error)throw b.error||p.error;setBanks(b.data||[]);setProofs(instructions?(p.data||[]).filter(x=>instructions.some(i=>i.id===x.invoice_id)):p.data||[]);
  if(instructions){if(platform==='schoolpro_subscription'&&instructions.length){const latest=await supabase.from('schoolpro_subscription_intents').select('*').in('id',instructions.map(i=>i.id)).eq('payer_user_id',user.id).order('created_at',{ascending:false});if(!current())return;if(latest.error)throw latest.error;setInvoices(latest.data||[]);}else setInvoices(instructions);}else{let q=supabase.from(tables[platform]).select('*').order('created_at',{ascending:false});if(['fabrication','compute','academy','digital_business','business_centre'].includes(platform)){const o=await supabase.from('business_orders').select('id').eq('user_id',user.id).eq('unit_code',platform);if(!current())return;if(o.error)throw o.error;const ids=(o.data||[]).map(x=>x.id);if(!ids.length){setInvoices([]);return;}q=q.in('order_id',ids);}const i=await q;if(!current())return;if(i.error)throw i.error;setInvoices(i.data||[]);}
 }catch(e){if(current())setError('Your payment records could not be loaded. Please refresh or contact support.');}finally{if(current())setLoading(false);}}
 useEffect(()=>{setSelected(null);setBanks([]);setInvoices([]);setProofs([]);setNotice('');setBusy(false);setError('');void load();},[user?.id,platform,instructions]);
 const due=(i:Row)=>Math.max(0,Number(i.amount)-Number(i.amount_paid||(i.status==='paid'?i.amount:0)));
 function choose(i:Row){setSelected(i);setFile(null);setNotice('');setError('');setForm({bank:'',sender:'',senderBank:'',reference:'',date:''});}
 async function submit(e:FormEvent){e.preventDefault();if(busy||!selected||!user||!supabase)return;setError('');setNotice('');if(!file||!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)||file.size===0||file.size>5*1024*1024){setError('Upload a PDF, JPG, PNG or WebP receipt up to 5 MB.');return;}if(!banks.some(b=>b.id===form.bank)){setError('Select the receiving bank used for your transfer.');return;}if(!form.sender.trim()||!form.reference.trim()||!form.date||!Number.isFinite(new Date(form.date).getTime())||new Date(form.date)>new Date()){setError('Enter the sender, bank reference and actual transfer date.');return;}const ownerScope=scope.current;setBusy(true);let path='';try{
  path=`${user.id}/${platform}/${selected.id}/${crypto.randomUUID()}.${file.type==='application/pdf'?'pdf':file.type.split('/')[1]}`;
  const up=await supabase.storage.from('direct-transfer-proofs').upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;
  const r=await supabase.rpc('submit_service_bank_transfer',{p_platform:platform,p_invoice:selected.id,p_bank_account:form.bank,p_source_reference:selected.invoice_number||selected.reference,p_amount:due(selected),p_sender_name:form.sender.trim(),p_sender_bank:form.senderBank.trim(),p_customer_reference:form.reference.trim(),p_transferred_at:new Date(form.date).toISOString(),p_proof_storage_path:path});if(r.error||!r.data){await supabase.storage.from('direct-transfer-proofs').remove([path]);throw r.error||new Error('No proof submission was saved.');}
  if(ownerScope!==scope.current)return;setNotice('Receipt submitted. Payment is awaiting Finance verification; the service has not been activated by this upload.');setSelected(null);setFile(null);await load();
 }catch(e){if(ownerScope===scope.current)setError('Your receipt could not be submitted. Refresh the invoice and try again, or contact support.');}finally{if(ownerScope===scope.current)setBusy(false);}}
 return <section className="space-y-5"><h2 className="text-2xl font-bold">Bank transfer payments</h2><p>Transfer the exact outstanding amount to either company account below. Include the invoice or subscription reference, then upload your receipt. Finance checks the bank statement before marking payment as received or activating the service.</p>
 <InvoiceRevisionInbox platform={platform} onRespond={()=>void load()}/>{error&&<p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-900">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-green-300 bg-green-50 p-4">{notice}</p>}
 <div className="grid gap-4 md:grid-cols-2">{banks.map(b=><article className="rounded-xl border bg-white p-5" key={b.id}><h3 className="font-bold">{b.bank_name}</h3><p className="mt-2 text-xl font-bold">{b.account_number}</p><p>{b.account_name}</p></article>)}</div>{!loading&&!banks.length&&<p role="alert">Company receiving accounts are unavailable. Contact support before transferring.</p>}
 <button type="button" disabled={loading||busy} className="rounded-lg border px-4 py-2" onClick={()=>{setError('');void load();}}>Refresh payment status</button><input aria-label="Search invoices" placeholder="Search invoices or subscription reference" className="block w-full rounded-lg border p-3" value={search} onChange={e=>setSearch(e.target.value)}/>
 {loading?<p role="status">Loading payment records…</p>:<div className="space-y-3">{invoices.filter(i=>String(i.invoice_number||i.reference||'').toLowerCase().includes(search.toLowerCase())).map(i=>{const pending=proofs.some(p=>p.invoice_id===i.id&&['pending','awaiting_verification'].includes(p.status)),canPay=platform==='schoolpro_subscription'?i.status==='pending':payable.includes(i.status);return <article key={i.id} className="rounded-xl border bg-white p-5"><h3 className="font-bold">{i.invoice_number||i.reference}</h3><p>{i.service_name||i.title||(platform==='schoolpro_subscription'?'Annual SchoolPro subscription':'Service invoice')} · {String(i.status).replaceAll('_',' ')}</p>{i.service_description&&<p className="mt-2 whitespace-pre-wrap">{i.service_description}</p>}<p className="text-sm break-all">Service reference: {i.project_id||i.order_id||i.school_id||i.id}</p>{i.replaces_invoice_id&&<p className="text-sm break-all">Replaces cancelled invoice: {i.replaces_invoice_id}</p>}<p className="mt-2">Outstanding: <b>{money(due(i))}</b></p>{pending?<p className="mt-2 font-bold">Receipt awaiting Finance verification</p>:canPay&&due(i)>0&&<button type="button" disabled={busy||!banks.length} className="mt-3 rounded-lg bg-blue-700 px-4 py-2 font-bold text-white" onClick={()=>choose(i)}>Submit payment proof</button>}</article>;})}{!invoices.length&&<p>No invoice or subscription payment instruction is available yet.</p>}</div>}
 {selected&&<form onSubmit={submit} className="space-y-4 rounded-xl border bg-white p-5"><h3 className="text-xl font-bold">Proof for {selected.invoice_number||selected.reference}</h3><p>Amount: {money(due(selected))}</p><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2"><label>Receiving account<select required className="mt-1 w-full rounded-lg border p-3" value={form.bank} onChange={e=>setForm({...form,bank:e.target.value})}><option value="">Choose the account you paid</option>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} — {b.account_number}</option>)}</select></label><label>Sender/account name<input required className="mt-1 w-full rounded-lg border p-3" value={form.sender} onChange={e=>setForm({...form,sender:e.target.value})}/></label><label>Sender bank<input className="mt-1 w-full rounded-lg border p-3" value={form.senderBank} onChange={e=>setForm({...form,senderBank:e.target.value})}/></label><label>Bank transaction reference<input required className="mt-1 w-full rounded-lg border p-3" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>Transfer date and time<input required type="datetime-local" className="mt-1 w-full rounded-lg border p-3" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Receipt (PDF/JPG/PNG/WebP, up to 5 MB)<input required type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="mt-1 block w-full" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="rounded-lg bg-blue-700 px-4 py-3 font-bold text-white">{busy?'Submitting receipt…':'Submit for verification'}</button><button type="button" className="rounded-lg border px-4 py-3" onClick={()=>setSelected(null)}>Cancel</button></fieldset></form>}
 <h3 className="text-xl font-bold">Payment proof history</h3><div className="space-y-3">{proofs.map(p=><article key={p.id} className="rounded-xl border p-4"><b>{p.source_reference} · {money(p.amount)}</b><p>Bank reference: {p.customer_reference}</p><p className="font-bold">{p.status.replaceAll('_',' ')}</p></article>)}{!loading&&!proofs.length&&<p>No payment proofs submitted yet.</p>}</div></section>;
}
