import {useCallback,useEffect,useRef,useState} from 'react';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
type Change={id:string;invoice_id:string;new_service_name:string;new_description:string;new_amount:number;reason:string;status:string};
export function InvoiceRevisionInbox({platform,onRespond}:{platform:string;onRespond:()=>void}){
 const {user}=useAuth();const generation=useRef(0);const [changes,setChanges]=useState<Change[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{const version=++generation.current;setChanges([]);setError('');if(!user||!supabase)return;const r=await supabase.from('service_invoice_changes').select('id,invoice_id,new_service_name,new_description,new_amount,reason,status').eq('user_id',user.id).eq('platform_code',platform).eq('status','pending').order('created_at',{ascending:false});if(version!==generation.current)return;if(r.error)setError(r.error.message);else setChanges(r.data||[]);},[user?.id,platform]);
 useEffect(()=>{void load();return()=>{generation.current++;};},[load]);
 async function respond(change:Change,accept:boolean){if(!supabase||busy)return;const version=generation.current;setBusy(true);setError('');try{const r=await supabase.rpc('respond_service_invoice_change',{p_change:change.id,p_accept:accept});if(r.error)throw r.error;if(version!==generation.current)return;await load();onRespond();}catch(e){if(version===generation.current)setError((e as Error).message);}finally{setBusy(false);}}
 if(!changes.length&&!error)return null;
 return <section className="space-y-3" aria-label="Invoice revisions">{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-900">Could not load invoice revisions: {error}</p>}{changes.map(c=><article key={c.id} className="space-y-3 rounded-xl border border-amber-300 bg-amber-50 p-4"><h3 className="text-lg font-bold">Review your revised invoice</h3><p className="font-bold">{c.new_service_name}</p><p className="whitespace-pre-wrap">{c.new_description}</p><p>New total: <b>NGN {Number(c.new_amount).toLocaleString('en-NG',{minimumFractionDigits:2})}</b></p><p>Reason: {c.reason}</p><p className="text-sm break-all">Invoice reference: {c.invoice_id}</p><p className="text-sm">Payment is paused. Accept to agree to these revised service details and price; reject to retain the previous terms.</p><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} className="min-h-11 rounded-lg bg-blue-700 px-4 py-3 font-bold text-white" onClick={()=>void respond(c,true)}>Accept revised terms</button><button type="button" disabled={busy} className="min-h-11 rounded-lg border px-4 py-3" onClick={()=>void respond(c,false)}>Reject revision</button></div></article>)}</section>;
}
