import {useEffect,useState} from 'react';
import {Fingerprint,LockKeyhole} from 'lucide-react';
import {androidVault,NativeVault,type VaultStatus} from '@/lib/nativeVault';
export function NativeAppSecurity(){
 const [status,setStatus]=useState<VaultStatus|null>(null),[current,setCurrent]=useState(''),[pin,setPin]=useState(''),[confirm,setConfirm]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(androidVault)void NativeVault.status().then(setStatus).catch(()=>setNotice('App security is unavailable. Please restart the app.'));},[]);
 if(!androidVault)return null;
 async function save(){if(pin.length!==6||pin!==confirm){setNotice('Enter and confirm the same six-digit passcode.');return;}setBusy(true);try{await NativeVault.configure({pin,currentPin:current});setStatus(await NativeVault.status());setCurrent('');setPin('');setConfirm('');window.dispatchEvent(new Event('ihlink:security-changed'));setNotice('App passcode saved. Enable fingerprint access below if you want to use it.');}catch{setNotice('Your passcode could not be saved. Check the current passcode and try again.');}finally{setBusy(false);}}
 async function biometric(){setBusy(true);try{if(status?.biometricEnabled)await NativeVault.disableBiometric();else await NativeVault.biometric({enable:true});setStatus(await NativeVault.status());window.dispatchEvent(new Event('ihlink:security-changed'));setNotice('Fingerprint preference updated.');}catch{setNotice('Fingerprint access could not be enabled. Check fingerprint settings on your phone.');}finally{setBusy(false);}}
 const input=(label:string,value:string,change:(v:string)=>void)=><label className="block text-sm font-semibold">{label}<input type="password" inputMode="numeric" autoComplete="off" maxLength={6} value={value} onChange={e=>change(e.target.value.replace(/\D/g,'').slice(0,6))} className="mt-2 w-full rounded-xl border p-3"/></label>;
 return <section className="app-card mb-5"><div className="flex items-center gap-3"><LockKeyhole/><h2 className="font-bold">App passcode & fingerprint</h2></div><p className="app-muted mt-3 text-sm">Unlock this app with a six-digit passcode. Your school account password stays separate. The app locks when you leave it or after two minutes without activity. Use your passcode or enabled fingerprint to return. Five incorrect attempts require signing in again.</p><div className="mt-4 grid gap-3">{status?.enabled&&input('Current app passcode',current,setCurrent)}{input('New six-digit app passcode',pin,setPin)}{input('Confirm app passcode',confirm,setConfirm)}<button disabled={busy||!status} type="button" className="app-action" onClick={()=>void save()}>{status?.enabled?'Change app passcode':'Set app passcode'}</button>{status?.enabled&&<><button type="button" disabled={busy||!status.biometricAvailable} className="app-action app-action-secondary" onClick={()=>void biometric()}><Fingerprint size={20}/>{status.biometricEnabled?'Disable fingerprint':'Enable fingerprint'}</button>{!status.biometricAvailable&&<p className="app-muted text-xs">Set up a supported fingerprint in your phone settings to use this option.</p>}<button type="button" className="app-action app-action-secondary" onClick={()=>window.dispatchEvent(new Event('ihlink:lock-app'))}>Lock app now</button></>}{notice&&<p role="status" className="text-sm">{notice}</p>}</div></section>;
}
