import {startAppIdleLock} from '@/lib/appIdleLock';
import {useEffect,useState,type ReactNode} from 'react';
import {App} from '@capacitor/app';
import {Fingerprint,LockKeyhole} from 'lucide-react';
import {androidVault,securitySupported,NativeVault,vaultLocked,vaultReady,type VaultStatus} from '@/lib/nativeVault';
import {supabase} from '@/lib/supabase';
export function NativeSessionGate({children}:{children:ReactNode}){
 const [status,setStatus]=useState<VaultStatus|null>(null),[pin,setPin]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!securitySupported)return;let active=true;async function check(){try{const value=await NativeVault.status();if(!active)return;setStatus(value);if(value.locked){vaultLocked();supabase?.auth.stopAutoRefresh();}else{if(androidVault||value.enabled)for(const key of Object.keys(localStorage))if(/^sb-.*-auth-token(?:-code-verifier)?$/.test(key))localStorage.removeItem(key);vaultReady();supabase?.auth.startAutoRefresh();}}catch{if(active)setError('App security could not be opened. Please restart the app.');}}
 void check();const listener=App.addListener('appStateChange',event=>{if(!event.isActive){void NativeVault.lock();vaultLocked();supabase?.auth.stopAutoRefresh();setStatus(value=>value?.enabled?{...value,locked:true}:value);setPin('');}else void check();});const lock=()=>{vaultLocked();supabase?.auth.stopAutoRefresh();setPin('');setStatus(value=>value?.enabled?{...value,locked:true}:value);void NativeVault.lock().then(check).catch(()=>{if(active)setError('Please restart the app to unlock securely.');});};window.addEventListener('ihlink:lock-app',lock);window.addEventListener('ihlink:security-changed',check);return()=>{active=false;window.removeEventListener('ihlink:lock-app',lock);window.removeEventListener('ihlink:security-changed',check);void listener.then(handle=>handle.remove());};},[]);
 useEffect(()=>{if(!status?.enabled||status.locked)return;return startAppIdleLock(()=>window.dispatchEvent(new Event('ihlink:lock-app')));},[status?.enabled,status?.locked]);
 async function unlock(biometric=false){setBusy(true);setError('');try{if(biometric)await NativeVault.biometric({});else await NativeVault.unlock({pin});const value=await NativeVault.status();setStatus(value);if(!value.locked){vaultReady();supabase?.auth.startAutoRefresh();}setPin('');}catch{const next=await NativeVault.status();if(!next.enabled){vaultReady();await supabase?.auth.signOut({scope:'local'});localStorage.setItem('ihlink.schoolpro.mobile.welcome.v1','done');window.location.assign('/schoolpro/login');}else{setError('We could not unlock the app. Check your passcode or sign in again.');setStatus(next);}}finally{setBusy(false);}}
 async function reset(){if(!window.confirm('Remove app access on this device and sign in again? Your school account and records will be kept.'))return;setBusy(true);try{await NativeVault.reset();vaultReady();await supabase?.auth.signOut({scope:'local'});setStatus(await NativeVault.status());window.location.assign('/schoolpro/login');}catch{setError('Please restart the app and try again.');}finally{setBusy(false);}}
 if(!securitySupported)return <>{children}</>;
 if(!status)return <main className="grid min-h-screen place-items-center p-6"><p role="status">{error||'Opening secure app access…'}</p></main>;
 return <><div hidden={status.locked}>{children}</div>{status.locked&&<main className="grid min-h-[100dvh] place-items-center bg-slate-950 p-5 text-white"><form className="w-full max-w-sm space-y-5" onSubmit={event=>{event.preventDefault();void unlock();}}><LockKeyhole className="mx-auto h-12 w-12 text-sky-300"/><h1 className="text-center text-2xl font-bold">Welcome back</h1><label className="block text-sm">Your six-digit app passcode<input autoFocus aria-label="App passcode" type="password" inputMode="numeric" autoComplete="off" maxLength={6} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,'').slice(0,6))} className="mt-2 min-h-14 w-full rounded-xl border bg-slate-800 p-3 text-center text-2xl tracking-[.5em]"/></label>{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}<button disabled={busy||pin.length!==6} className="min-h-12 w-full rounded-xl bg-sky-600 p-3 font-bold disabled:opacity-50">{busy?'Unlocking…':'Unlock app'}</button>{status.biometricEnabled&&status.biometricAvailable&&<button type="button" disabled={busy} className="flex min-h-12 w-full items-center justify-center gap-3 rounded-xl border p-3" onClick={()=>void unlock(true)}><Fingerprint/>Use fingerprint</button>}<button type="button" disabled={busy} className="min-h-12 w-full p-3 text-sm" onClick={()=>void reset()}>Forgot passcode? Sign in again</button></form></main>}</>;
}
