import {useEffect,useState,useRef} from 'react';
import {Fingerprint,LockKeyhole} from 'lucide-react';
import {androidVault,securitySupported,NativeVault,type VaultStatus} from '@/lib/nativeVault';
export function NativeAppSecurity({setupOnly=false}:{setupOnly?:boolean}){
 const action=useRef(false);
 const [status,setStatus]=useState<VaultStatus|null>(null),[current,setCurrent]=useState(''),[pin,setPin]=useState(''),[confirm,setConfirm]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(securitySupported)void NativeVault.status().then(setStatus).catch(()=>setNotice('App security is unavailable. Please restart the app.'));},[]);
 if(!securitySupported)return null;
 async function save(){if(action.current)return;if(pin.length!==6||pin!==confirm){setNotice('Enter and confirm the same six-digit passcode.');return;}action.current=true;setBusy(true);try{await NativeVault.configure({pin,currentPin:current});setStatus(await NativeVault.status());setCurrent('');setPin('');setConfirm('');window.dispatchEvent(new Event('ihlink:security-changed'));setNotice(androidVault?'App passcode saved. You can enable fingerprint below.':'App passcode saved.');}catch{setNotice('Your passcode could not be saved. Check the current passcode and try again.');}finally{action.current=false;setBusy(false);}}
 async function biometric(){if(action.current)return;action.current=true;setBusy(true);try{if(status?.biometricEnabled)await NativeVault.disableBiometric();else await NativeVault.biometric({enable:true});setStatus(await NativeVault.status());window.dispatchEvent(new Event('ihlink:security-changed'));setNotice('Fingerprint preference updated.');}catch{setNotice('Fingerprint access could not be enabled. Check fingerprint or device-unlock settings.');}finally{action.current=false;setBusy(false);}}
 const input=(label:string,value:string,change:(v:string)=>void)=><label className="block text-sm font-semibold">{label}<input type="password" inputMode="numeric" autoComplete="off" maxLength={6} value={value} onChange={e=>change(e.target.value.replace(/\D/g,'').slice(0,6))} className="mt-2 w-full rounded-xl border p-3"/></label>;
 return <section className="app-card mb-5"><div className="flex items-center gap-3"><LockKeyhole/><h2 className="font-bold">{androidVault?'App passcode & fingerprint':'App passcode'}</h2></div><p className="app-muted mt-3 text-sm">Unlock this app with a six-digit passcode. Your school account password stays separate. The app locks when you leave it or after two minutes without activity. Use your passcode to return. Five incorrect attempts require signing in again.</p><div className="mt-4 grid gap-3">{(!setupOnly||!status?.enabled)&&<>{status?.enabled&&input('Current app passcode',current,setCurrent)}{input(status?.enabled?'New six-digit app passcode':'Six-digit app passcode',pin,setPin)}{input('Confirm app passcode',confirm,setConfirm)}<button disabled={busy||!status} type="button" className="app-action" onClick={()=>void save()}>{busy?'Saving passcode…':status?.enabled?'Change app passcode':'Set app passcode'}</button></>}{status?.enabled&&<>{androidVault&&<><button type="button" disabled={busy||!status.biometricAvailable} className="app-action app-action-secondary" onClick={()=>void biometric()}><Fingerprint size={20}/>{busy?'Waiting for device unlock…':status.biometricEnabled?'Disable fingerprint':'Enable fingerprint / device unlock'}</button>{!status.biometricAvailable&&<p className="app-muted text-xs">Device unlock requires a supported authenticator. You can continue using your passcode.</p>}</>}{!setupOnly&&<button type="button" className="app-action app-action-secondary" onClick={()=>window.dispatchEvent(new Event('ihlink:lock-app'))}>Lock app now</button>}{setupOnly&&androidVault&&!status.biometricEnabled&&<button type="button" disabled={busy} className="app-action app-action-secondary" onClick={()=>{localStorage.setItem('ihlink.'+ 'schoolpro'+'.fingerprint-choice','skipped');window.dispatchEvent(new Event('ihlink:security-changed'));}}>Continue with passcode</button>}</>}{notice&&<p role="status" className="text-sm">{notice}</p>}</div></section>;
}
