import {Link} from 'react-router-dom';
import {useAuth} from '@/context/AuthContext';
import {useSchoolProContext} from '@/hooks/useSchoolProContext';
import {GraduationCap,BookOpen,Users,LifeBuoy,ChevronRight} from 'lucide-react';
export function NativeAppHome(){
 const {user}=useAuth(); const school=useSchoolProContext(); const role=school.role.toLowerCase();
 const dashboard=role==='student'?'/schoolpro/student-dashboard':role==='parent'?'/schoolpro/parent-dashboard':role==='teacher'?'/schoolpro/teacher-dashboard':role==='proprietor'?'/schoolpro/proprietor-dashboard':'/schoolpro/admin-dashboard';
 const connected=Boolean(user&&school.schoolId&&!school.loading&&!school.error);
 const actions=connected?[{label:'My school',to:dashboard,icon:GraduationCap},{label:'Check results',to:'/schoolpro/result-checker',icon:BookOpen},{label:'My account',to:'/schoolpro/profile',icon:Users},{label:'Support',to:'/schoolpro/get-in-touch',icon:LifeBuoy}]:[{label:'School sign in',to:'/schoolpro/login',icon:GraduationCap},{label:'Teacher sign in',to:'/schoolpro/teacher-login',icon:Users},{label:'Parent sign in',to:'/schoolpro/parent-login',icon:Users},{label:'Student sign in',to:'/schoolpro/student-login',icon:BookOpen}];
 return <main className="app-page"><section><p className="app-muted text-sm">Your school community</p><h1 className="mt-1 text-2xl font-extrabold">{connected?school.schoolName:'Run Your School Smarter'}</h1></section><section className="app-card"><GraduationCap size={36}/><h2 className="mt-4 text-xl font-bold">{connected?'Your school, in your pocket':'Welcome to SchoolPro'}</h2><p className="app-muted mt-2 text-sm">{connected?'Open your school workspace or check a result.':'Choose your sign-in below to access your school.'}</p>{connected&&<Link to={dashboard} className="app-action mt-5">Open my school<ChevronRight size={18}/></Link>}{school.loading&&<p role="status" className="app-muted mt-4 text-sm">Loading your school…</p>}{school.error&&user&&<p role="status" className="mt-4 text-sm text-rose-700">Your school access could not be loaded. Please try again.</p>}</section><section><h2 className="mb-4 text-lg font-bold">{connected?'Quick access':'Sign in as'}</h2><div className="grid grid-cols-2 gap-3">{actions.map(({label,to,icon:Icon})=><Link key={to} to={to} className="app-service"><Icon size={26}/>{label}</Link>)}</div></section><section className="app-card"><h2 className="font-bold">Check a result</h2><p className="app-muted mt-2 text-sm">Use the details provided by your school.</p><Link to="/schoolpro/result-checker" className="app-action mt-4">Open result checker<ChevronRight size={18}/></Link></section>{!connected&&!school.loading&&<Link to="/schoolpro/register" className="app-action app-action-secondary">Register your school</Link>}<Link to="/schoolpro/get-in-touch" className="flex min-h-11 items-center justify-center gap-2 text-sm"><LifeBuoy size={18}/>Need help?</Link></main>;
}
