import {useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/context/AuthContext';
export function SchoolProTermDemoForm({requestId,tier,onSubmitted}:{requestId:string;tier:string;onSubmitted:()=>Promise<void>}){
 const {user}=useAuth();const [dates,setDates]=useState({term_start:'',term_end:'',exam_start:'',exam_end:''}),[calendar,setCalendar]=useState<File|null>(null),[letter,setLetter]=useState<File|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function submit(){if(!supabase||!user||busy)return;if(!calendar||!letter||Object.values(dates).some(v=>!v)){setNotice('Enter all dates and upload your calendar and request letter.');return;}
 if([calendar,letter].some(f=>f.size>10*1024*1024||!['application/pdf','image/jpeg','image/png'].includes(f.type))){setNotice('Use PDF, JPG or PNG documents up to 10 MB each.');return;}
 setBusy(true);setNotice('');try{const db=supabase;async function upload(f:File,label:string){const ext=f.type==='application/pdf'?'pdf':f.type==='image/png'?'png':'jpg';const path=`${user!.id}/${requestId}/${crypto.randomUUID()}-${label}.${ext}`;const r=await db.storage.from('schoolpro-demo-documents').upload(path,f,{contentType:f.type,upsert:false});if(r.error)throw r.error;return path;}
 const calendarPath=await upload(calendar,'calendar'),letterPath=await upload(letter,'letter');const r=await db.rpc('submit_schoolpro_term_demo',{p_request:requestId,p_tier:tier,p_term_start:dates.term_start,p_term_end:dates.term_end,p_exam_start:dates.exam_start,p_exam_end:dates.exam_end,p_calendar:calendarPath,p_letter:letterPath});if(r.error)throw r.error;setNotice('Submitted for calendar review. Your demo starts only after approval.');await onSubmitted();
 }catch{setNotice('Submission could not be completed. Check that your term spans at least three months and your exam dates fall within it.');}finally{setBusy(false);}}
 return <section className="mt-3 grid min-w-0 gap-3 rounded-xl border p-3"><h4 className="font-semibold">Request a term demo</h4><p className="text-sm">Submit your school calendar and request letter for approval. The term must span at least three months. Access ends at term end or 14 days after exams finish, whichever is later. Afterward, choose an annual paid plan.</p><div className="grid gap-3 sm:grid-cols-2">{(['term_start','term_end','exam_start','exam_end'] as const).map(k=><label key={k} className="min-w-0 text-sm">{k.replace('_',' ')}<input type="date" className="mt-1 block w-full min-w-0 rounded-lg border p-2" value={dates[k]} onChange={e=>setDates(v=>({...v,[k]:e.target.value}))}/></label>)}</div><label className="text-sm">Term calendar<input type="file" accept="application/pdf,image/png,image/jpeg" className="mt-1 block w-full min-w-0" onChange={e=>setCalendar(e.target.files?.[0]||null)}/></label><label className="text-sm">Request letter<input type="file" accept="application/pdf,image/png,image/jpeg" className="mt-1 block w-full min-w-0" onChange={e=>setLetter(e.target.files?.[0]||null)}/></label><button type="button" disabled={busy} className="min-h-11 rounded-xl border px-3 font-semibold" onClick={()=>void submit()}>{busy?'Submitting…':'Submit calendar for review'}</button>{notice&&<p role="status" className="text-sm">{notice}</p>}</section>;
}
