import {useState,type FormEvent} from 'react';
import {supabase} from '@/lib/supabase';
import {Button} from '@/components/ui/Button';
export function SchoolFeeEditor({record,kind,onSaved}:{record:any;kind:'invoice'|'structure';onSaved:()=>Promise<unknown>}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const[draft,setDraft]=useState({title:'',amount:'',due:'',notes:''});
 const allowed=kind==='structure'||(record.status==='unpaid'&&Number(record.amount_paid||0)===0);
 async function save(event:FormEvent){event.preventDefault();if(!supabase||busy)return;const amount=Number(draft.amount);if(!draft.title.trim()||!draft.amount.trim()||!Number.isFinite(amount)||amount<0||Math.abs(amount*100-Math.round(amount*100))>0.000001)return setNotice('Enter a name and an amount of zero or more, with up to two decimal places.');setBusy(true);setNotice('');try{const result=kind==='invoice'?await supabase.rpc('edit_schoolpro_fee_invoice',{p_invoice:record.id,p_title:draft.title.trim(),p_amount:amount,p_due:draft.due||null,p_notes:draft.notes.trim()||null}):await supabase.from('schoolpro_fee_structures').update({name:draft.title.trim(),amount,due_date:draft.due||null,updated_at:new Date().toISOString()}).eq('id',record.id).eq('school_id',record.school_id).select('id').single();if(result.error)throw result.error;await onSaved();setOpen(false);setNotice('Changes saved.');}catch(error){const text=String((error as any)?.message||'');setNotice(/pending|payment/i.test(text)?'Review the pending payment or recorded receipt before changing this invoice.':/permission|authoriz|access/i.test(text)?'Your account does not have permission to edit this fee.':'This fee could not be saved. Please check the values and try again.');}finally{setBusy(false)}}
 return <div className="mt-3"><Button type="button" variant="secondary" size="sm" disabled={!allowed||busy} onClick={()=>{setDraft({title:kind==='invoice'?record.title:record.name,amount:String(kind==='invoice'?record.amount_due:record.amount),due:record.due_date||'',notes:record.notes||''});setNotice('');setOpen(!open)}}>{open?'Close editor':kind==='invoice'?'Edit invoice':'Edit fee structure'}</Button>{!allowed&&<p className="mt-1 text-xs">Recorded payments are retained. This invoice cannot be edited.</p>}{notice&&<p role="status" className="mt-2 text-sm">{notice}</p>}{open&&<form onSubmit={save} className="mt-3 grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><label className="text-sm">{kind==='invoice'?'Invoice title':'Fee structure name'}<input required maxLength={200} className="mt-1 w-full rounded-lg border p-3" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="text-sm">Amount (₦)<input required type="number" min="0" step="0.01" className="mt-1 w-full rounded-lg border p-3" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label className="text-sm">Due date<input type="date" className="mt-1 w-full rounded-lg border p-3" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></label>{kind==='invoice'&&<label className="text-sm">Notes<textarea className="mt-1 w-full rounded-lg border p-3" maxLength={2000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>}<Button disabled={busy}>{busy?'Saving…':'Save changes'}</Button></form>}</div>
}
