import {useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '@/context/AuthContext';
import {supabase} from '@/lib/supabase';
const labels:Record<string,string>={submitted:'Awaiting review',reviewing:'Under review',approved:'Ready to create your workspace',provisioning:'Workspace ready — subscription pending',active:'Ready to use',rejected:'Please contact support'};
type Request={id:string;school_name:string;status:string;school_id:string|null};
export function SchoolProOnboardingStatus(){
 const {user}=useAuth();const announced=useRef('');const [state,setState]=useState<{userId:string;rows:Request[];error:boolean}>({userId:'',rows:[],error:false});const [busy,setBusy]=useState(false),[action,setAction]=useState(''),[notice,setNotice]=useState(''),[tier,setTier]=useState('starter'),[plans,setPlans]=useState<{code:string;name:string}[]>([]);
 const load=useCallback(async()=>{if(!supabase||!user)return;setBusy(true);try{
  await supabase.rpc('claim_schoolpro_onboarding');
  const catalog=await supabase.from('schoolpro_subscription_catalog').select('code,name').eq('active',true);setPlans(catalog.data||[]);
  const {data,error}=await supabase.from('schoolpro_onboarding_requests').select('id,school_name,status,school_id').eq('user_id',user.id).order('created_at',{ascending:false}).limit(10);
  setState({userId:user.id,rows:error?[]:data||[],error:Boolean(error)});
  const signature=user.id+':'+(data||[]).filter(r=>r.school_id).map(r=>r.school_id+':'+r.status).sort().join(',');if(data?.some(r=>r.school_id)&&signature!==announced.current){announced.current=signature;window.dispatchEvent(new Event('ihlink:school-refresh'));}
 }catch{setState({userId:user.id,rows:[],error:true});}finally{setBusy(false);}},[user?.id]);
 useEffect(()=>{if(!user)return;void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);};},[load,user?.id]);
 async function create(request:Request){if(!supabase||action)return;setAction(request.id);setNotice('');try{const r=await supabase.rpc('create_schoolpro_workspace',{p_request:request.id,p_tier:tier});if(r.error)throw r.error;const email=await supabase.functions.invoke('schoolpro-owner-access',{body:{school_id:r.data.school_id}});setNotice('Your workspace and subscription invoice are ready. '+(!email.error&&email.data?.password_email_requested?'Check your email for account access.':'You can sign in with your existing password; the access email needs retry.'));await load();}catch{setNotice('Your workspace could not be created. Check that your email is verified, or contact support.');}finally{setAction('');}}
 async function resend(request:Request){if(!supabase||!request.school_id||action)return;setAction(request.id);try{const r=await supabase.functions.invoke('schoolpro-owner-access',{body:{school_id:request.school_id}});setNotice(!r.error&&r.data?.password_email_requested?'Account access email requested. Please check your inbox.':'Email could not be requested. Please try later or contact support.');}finally{setAction('');}}
 if(!user||state.userId!==user.id||(!state.error&&!state.rows.length))return null;
 return <section className="app-card rounded-2xl border p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">My school requests</h2><button type="button" disabled={busy} className="min-h-11 text-sm font-semibold" onClick={()=>void load()}>{busy?'Refreshing…':'Refresh'}</button></div>{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}{state.error?<p role="status" className="mt-3 text-sm">Your school request status could not be loaded. Please try again.</p>:state.rows.map(r=><div key={r.id} className="mt-3 rounded-xl border p-3"><h3 className="font-semibold">{r.school_name.trim()}</h3><p className="mt-1 text-sm">{labels[r.status]||'Under review'}</p><p className="mt-1 text-xs text-muted">Reference: {r.id.slice(0,8).toUpperCase()}</p>{!r.school_id&&['submitted','reviewing','approved'].includes(r.status)&&<div className="mt-3 space-y-2"><label className="block text-sm">School plan<select value={tier} onChange={e=>setTier(e.target.value)} className="ml-2 rounded-xl border p-2">{plans.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select></label><button type="button" disabled={Boolean(action)||!plans.some(p=>p.code===tier)} className="min-h-11 rounded-xl border px-3 font-semibold" onClick={()=>void create(r)}>{action===r.id?'Creating…':'Create workspace & invoice'}</button></div>}{r.school_id&&<Link to={`/schoolpro/proprietor-dashboard?school_id=${r.school_id}`} className="mt-3 inline-flex min-h-11 items-center font-semibold">Open school workspace</Link>}{r.school_id&&<div className="mt-2 flex flex-wrap gap-3"><Link to={`/schoolpro/subscription?school_id=${r.school_id}`} className="inline-flex min-h-11 items-center font-semibold">View subscription invoice</Link><button type="button" disabled={Boolean(action)} className="min-h-11 text-sm" onClick={()=>void resend(r)}>Resend access email</button></div>}</div>)}</section>;
}
