import {SchoolStudentFilters} from './SchoolStudentFilters';
import {schoolStaffRoles} from '@/lib/schoolStaffRoles';
import {useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/Button';
import {supabase} from '@/lib/supabase';
type Child={id:string;first_name:string;last_name:string;admission_number:string;class_id?:string|null;class_name?:string|null};
export function SchoolAccountForm({schoolId,childrenList=[],parent=false,onAdded}:{schoolId:string;childrenList?:Child[];parent?:boolean;onAdded:()=>Promise<void>}){
 const [form,setForm]=useState({firstName:'',middleName:'',surname:'',email:'',role:parent?'parent':'teacher',relationship:'guardian'});
 const [visibleIds,setVisibleIds]=useState<string[]>(childrenList.map(c=>c.id));
 const [selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[code,setCode]=useState('');
 async function submit(event:FormEvent){
  event.preventDefault();if(!supabase||busy)return;setBusy(true);setMessage('');setCode('');
  try{
   const {data,error}=await supabase.functions.invoke('invite-school-staff',{body:{schoolId,...form,role:parent?'parent':form.role,studentIds:selected}});
   if(error||data?.error){let feedback=data?.error;if(!feedback&&error?.context instanceof Response){const body=await error.context.clone().json().catch(()=>null);feedback=body?.error;}setMessage(feedback||'The account could not be added. Please try again.');return;}
   setCode(data.schoolCode||'');
   if(data.requiresAcceptance){setMessage(`${data.email} already has an IHLink account. Share the school code with them. They must sign in with their existing email and password and enter this school code within seven days.`);}
   else setMessage(`${data.email} can now sign in to SchoolPro using ${data.surname?`the registered surname (${data.surname})`:"their surname"} as the first password. They must choose a new password before opening school records. First-time access expires in seven days.`);
   setForm({...form,firstName:'',middleName:'',surname:'',email:''});setSelected([]);await onAdded();
  }catch{setMessage('The account could not be added. Please try again.');}finally{setBusy(false);}
 }
 return <form onSubmit={event=>void submit(event)} className="mt-4 grid min-w-0 gap-3"><p className="text-sm text-muted">New accounts use their surname for first sign-in, then choose their own password. Share the details privately; no email delivery is needed.</p>{(['firstName','middleName','surname','email']as const).map(key=><label key={key} className="text-sm font-semibold">{{firstName:'First name',middleName:'Middle name',surname:'Surname',email:'Email'}[key]}<input required type={key==='email'?'email':'text'} maxLength={key==='email'?254:100} className="mt-1 w-full min-w-0 rounded-lg border p-3" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} disabled={busy}/></label>)}{parent?<><SchoolStudentFilters schoolId={schoolId} students={childrenList} onChange={setVisibleIds}/><p className="text-xs text-muted">{selected.length} children selected. Changing a filter keeps your selections.</p><fieldset className="max-h-64 overflow-y-auto rounded-lg border p-3"><legend className="text-sm font-semibold">Enrolled children</legend>{childrenList.filter(c=>visibleIds.includes(c.id)).map(child=><label key={child.id} className="flex gap-3 py-2 text-sm"><input type="checkbox" checked={selected.includes(child.id)} disabled={busy} onChange={e=>setSelected(e.target.checked?[...selected,child.id]:selected.filter(id=>id!==child.id))}/><span>{child.first_name} {child.last_name} · {child.admission_number}</span></label>)}{!childrenList.length&&<p className="text-sm text-muted">Enrol a child before adding parent access.</p>}</fieldset><label className="text-sm font-semibold">Relationship<select value={form.relationship} className="mt-1 w-full rounded-lg border p-3" onChange={e=>setForm({...form,relationship:e.target.value})}>{['mother','father','guardian','sponsor'].map(x=><option key={x} value={x}>{x}</option>)}</select></label></>:<label className="text-sm font-semibold">Access role<select value={form.role} className="mt-1 w-full rounded-lg border p-3" onChange={e=>setForm({...form,role:e.target.value})}>{schoolStaffRoles.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}<Button disabled={busy||!schoolId||(parent&&!selected.length)}>{busy?'Adding…':parent?'Add parent and link children':'Add staff account'}</Button>{message&&<p role="status" className="break-words rounded-lg bg-purple-50 p-3 text-sm">{message}</p>}{code&&<div className="rounded-lg border p-3"><label className="text-sm font-semibold">School code<input readOnly className="mt-1 w-full min-w-0 rounded-lg border p-2 text-sm" value={code}/></label><p className="mt-2 text-xs text-muted">Copy this code now. It is shown only for this request.</p></div>}</form>;
}
