import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useSchoolProContext} from '@/hooks/useSchoolProContext';
import {schoolSection} from '@/lib/schoolClassFilters';
import {Card} from './ui/Card';import {Button} from './ui/Button';
type Student={id:string;first_name:string;last_name:string;class_id:string|null;class_name:string};
export function SchoolNoticeComposer(){
 const ctx=useSchoolProContext(),role=ctx.role.toLowerCase().replaceAll('_',' ');const leader=['proprietor','administrator','super administrator','vice principal','head teacher'].includes(role);const canSend=leader||['teacher','class teacher'].includes(role);
 const [classes,setClasses]=useState<any[]>([]),[students,setStudents]=useState<Student[]>([]),[section,setSection]=useState(''),[classId,setClassId]=useState(''),[studentId,setStudentId]=useState(''),[audience,setAudience]=useState('families'),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;setClasses([]);setStudents([]);setSection('');setClassId('');setStudentId('');if(supabase&&ctx.schoolId&&canSend)void Promise.all([supabase.from('schoolpro_classes').select('id,name,arm,level').eq('school_id',ctx.schoolId),supabase.from('schoolpro_students').select('id,first_name,last_name,class_id,class_name').eq('school_id',ctx.schoolId).eq('status','active')]).then(([a,b])=>{if(current){setClasses(a.data||[]);setStudents(b.data||[]);if(a.error||b.error)setFeedback('Notice recipients could not be loaded. Please refresh.')}});return()=>{current=false}},[ctx.schoolId,canSend]);
 const scopedClasses=useMemo(()=>classes.filter(c=>!section||schoolSection(c.level,c.name)===section),[section,classes]);const eligible=students.filter(s=>(!classId||s.class_id===classId)&&(!section||scopedClasses.some(c=>c.id===s.class_id)));
 async function send(){if(!supabase||!ctx.schoolId||busy)return;setBusy(true);setFeedback('');const {data,error}=await (supabase as any).rpc('schoolpro_send_school_notice',{p_school:ctx.schoolId,p_title:title,p_message:message,p_audience:audience,p_classes:classId?[classId]:section?scopedClasses.map(c=>c.id):null,p_students:studentId?[studentId]:null});setBusy(false);setFeedback(error?'The notice could not be sent. Check the selected audience and your school permission.':`Notice delivered to ${data} school accounts. Only enrolled students and linked parents with accounts receive app notices.`);if(!error){setTitle('');setMessage('')}}
 if(!canSend)return null;const field='mt-1 w-full min-w-0 rounded-xl border p-3 text-sm';
 return <Card><h3 className="font-bold">Send a school notice</h3><p className="mt-1 text-sm text-muted">{leader?'Choose the whole school, one section, class or student.':'Send to students and parents in your assigned classes.'}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Section<select className={field} value={section} onChange={e=>{setSection(e.target.value);setClassId('');setStudentId('')}}><option value="">{leader?'All school sections':'All assigned sections'}</option>{[...new Set(classes.map(c=>schoolSection(c.level,c.name)))].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm font-semibold">Class<select className={field} value={classId} onChange={e=>{setClassId(e.target.value);setStudentId('')}}><option value="">All classes in this selection</option>{scopedClasses.map(c=><option key={c.id} value={c.id}>{c.name} {c.arm||''}</option>)}</select></label><label className="text-sm font-semibold">Student<select className={field} value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">All students in this selection</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.class_name}</option>)}</select></label><label className="text-sm font-semibold">Recipients<select className={field} value={audience} onChange={e=>setAudience(e.target.value)}><option value="families">Students and linked parents</option>{leader&&<><option value="staff">Staff</option><option value="all">Staff, students and linked parents</option></>}</select></label></div><label className="mt-3 block text-sm font-semibold">Title<input className={field} value={title} onChange={e=>setTitle(e.target.value)} maxLength={150}/></label><label className="mt-3 block text-sm font-semibold">Message<textarea className={field} value={message} onChange={e=>setMessage(e.target.value)} rows={4} maxLength={4000}/></label><Button className="mt-3" disabled={busy||!title.trim()||!message.trim()} onClick={()=>void send()}>{busy?'Sending…':'Send notice'}</Button>{feedback&&<p role="status" className="mt-3 text-sm">{feedback}</p>}</Card>;
}
