-- SchoolPro document and certificate template studio.
-- Private school-scoped source templates, dynamic field mappings and issuance audit records.
create table if not exists public.schoolpro_document_templates(
 id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,name text not null,document_type text not null,description text,source_format text not null check(source_format in('pdf','docx','image')),storage_path text not null,original_filename text not null,mime_type text not null,page_count integer,field_mappings jsonb not null default '[]'::jsonb,settings jsonb not null default '{}'::jsonb,is_active boolean not null default true,is_default boolean not null default false,version integer not null default 1,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,document_type,name,version));
create table if not exists public.schoolpro_document_issues(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,template_id uuid references public.schoolpro_document_templates(id) on delete set null,student_id uuid references public.schoolpro_students(id) on delete set null,document_type text not null,title text not null,serial_number text not null default ('DOC-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12))),payload jsonb not null default '{}'::jsonb,output_storage_path text,status text not null default 'draft' check(status in('draft','issued','revoked')),issued_at timestamptz,issued_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(school_id,serial_number));
alter table public.schoolpro_document_templates enable row level security;alter table public.schoolpro_document_issues enable row level security;
grant select,insert,update,delete on public.schoolpro_document_templates,public.schoolpro_document_issues to authenticated;
create policy "school members read document templates" on public.schoolpro_document_templates for select to authenticated using(exists(select 1 from public.schoolpro_schools s where s.id=school_id and s.owner_id=auth.uid()) or exists(select 1 from public.schoolpro_members m where m.school_id=school_id and m.user_id=auth.uid()));
create policy "school managers manage document templates" on public.schoolpro_document_templates for all to authenticated using(public.schoolpro_member_can_manage(school_id)) with check(public.schoolpro_member_can_manage(school_id));
create policy "school members read document issues" on public.schoolpro_document_issues for select to authenticated using(exists(select 1 from public.schoolpro_schools s where s.id=school_id and s.owner_id=auth.uid()) or exists(select 1 from public.schoolpro_members m where m.school_id=school_id and m.user_id=auth.uid()) or exists(select 1 from public.schoolpro_students st where st.id=student_id and st.user_id=auth.uid()));
create policy "school managers manage document issues" on public.schoolpro_document_issues for all to authenticated using(public.schoolpro_member_can_manage(school_id) or exists(select 1 from public.schoolpro_members m where m.school_id=school_id and m.user_id=auth.uid() and m.role::text in('registrar','head_teacher','vice_principal'))) with check(public.schoolpro_member_can_manage(school_id) or exists(select 1 from public.schoolpro_members m where m.school_id=school_id and m.user_id=auth.uid() and m.role::text in('registrar','head_teacher','vice_principal')));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('schoolpro-document-templates','schoolpro-document-templates',false,15728640,array['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','image/png','image/jpeg']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "schoolpro template objects read" on storage.objects for select to authenticated using(bucket_id='schoolpro-document-templates' and ((storage.foldername(name))[1] in(select s.id::text from public.schoolpro_schools s where s.owner_id=auth.uid()) or (storage.foldername(name))[1] in(select m.school_id::text from public.schoolpro_members m where m.user_id=auth.uid())));
create policy "schoolpro template objects insert" on storage.objects for insert to authenticated with check(bucket_id='schoolpro-document-templates' and (storage.foldername(name))[1] in(select s.id::text from public.schoolpro_schools s where s.owner_id=auth.uid() union select m.school_id::text from public.schoolpro_members m where m.user_id=auth.uid() and m.role::text in('proprietor','administrator','it_admin')));
create policy "schoolpro template objects update" on storage.objects for update to authenticated using(bucket_id='schoolpro-document-templates' and (storage.foldername(name))[1] in(select s.id::text from public.schoolpro_schools s where s.owner_id=auth.uid() union select m.school_id::text from public.schoolpro_members m where m.user_id=auth.uid() and m.role::text in('proprietor','administrator','it_admin'))) with check(bucket_id='schoolpro-document-templates' and (storage.foldername(name))[1] in(select s.id::text from public.schoolpro_schools s where s.owner_id=auth.uid() union select m.school_id::text from public.schoolpro_members m where m.user_id=auth.uid() and m.role::text in('proprietor','administrator','it_admin')));
create policy "schoolpro template objects delete" on storage.objects for delete to authenticated using(bucket_id='schoolpro-document-templates' and (storage.foldername(name))[1] in(select s.id::text from public.schoolpro_schools s where s.owner_id=auth.uid() union select m.school_id::text from public.schoolpro_members m where m.user_id=auth.uid() and m.role::text in('proprietor','administrator','it_admin')));