-- SchoolPro invoice studio, fee line items, member permissions and notifications. Live database includes the corresponding RLS policies and private invoice-template storage policies.
create table if not exists public.schoolpro_invoice_templates(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,name text not null,source_format text not null default 'builtin',storage_path text,layout jsonb not null default '{}'::jsonb,is_default boolean not null default false,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schoolpro_fee_items(id uuid primary key default gen_random_uuid(),fee_structure_id uuid not null references public.schoolpro_fee_structures(id) on delete cascade,label text not null,amount numeric not null check(amount>=0),category text not null default 'fee',sort_order int not null default 0,is_optional boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.schoolpro_member_permissions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,member_id uuid not null references public.schoolpro_members(id) on delete cascade,permission text not null,allowed boolean not null default true,updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),unique(member_id,permission));
create table if not exists public.schoolpro_notifications(id uuid primary key default gen_random_uuid(),school_id uuid references public.schoolpro_schools(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,title text not null,message text not null,kind text not null default 'info',href text,read_at timestamptz,created_at timestamptz not null default now());
alter table public.schoolpro_invoice_templates enable row level security;alter table public.schoolpro_fee_items enable row level security;alter table public.schoolpro_member_permissions enable row level security;alter table public.schoolpro_notifications enable row level security;
grant select,insert,update,delete on public.schoolpro_invoice_templates,public.schoolpro_fee_items,public.schoolpro_member_permissions,public.schoolpro_notifications to authenticated;
create policy "school invoice template access" on public.schoolpro_invoice_templates for all to authenticated using(private.has_school_access(school_id)) with check(private.has_school_access(school_id));
create policy "school fee item access" on public.schoolpro_fee_items for all to authenticated using(exists(select 1 from public.schoolpro_fee_structures f where f.id=fee_structure_id and private.has_school_access(f.school_id))) with check(exists(select 1 from public.schoolpro_fee_structures f where f.id=fee_structure_id and private.has_school_access(f.school_id)));
create policy "school permission read" on public.schoolpro_member_permissions for select to authenticated using(private.has_school_access(school_id));
create policy "school permission manage" on public.schoolpro_member_permissions for all to authenticated using(private.has_school_access(school_id,array['proprietor','administrator','it_admin']::public.school_member_role[])) with check(private.has_school_access(school_id,array['proprietor','administrator','it_admin']::public.school_member_role[]));
create policy "own schoolpro notifications" on public.schoolpro_notifications for select to authenticated using(user_id=auth.uid());
create policy "update own schoolpro notifications" on public.schoolpro_notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
insert into storage.buckets(id,name,public) values('schoolpro-invoice-templates','schoolpro-invoice-templates',false) on conflict(id) do nothing;
create policy "schoolpro invoice template storage read" on storage.objects for select to authenticated using(bucket_id='schoolpro-invoice-templates');
create policy "schoolpro invoice template storage write" on storage.objects for insert to authenticated with check(bucket_id='schoolpro-invoice-templates' and private.has_school_access((storage.foldername(name))[1]::uuid));
create policy "schoolpro invoice template storage update" on storage.objects for update to authenticated using(bucket_id='schoolpro-invoice-templates' and private.has_school_access((storage.foldername(name))[1]::uuid)) with check(bucket_id='schoolpro-invoice-templates' and private.has_school_access((storage.foldername(name))[1]::uuid));
create policy "schoolpro invoice template storage delete" on storage.objects for delete to authenticated using(bucket_id='schoolpro-invoice-templates' and private.has_school_access((storage.foldername(name))[1]::uuid));
-- Effective permission RPC is role-based and applies explicit member allow/deny overrides; live deployment revokes anon/PUBLIC execute.
-- Notification triggers fan out announcements, admission changes and generated invoices to school staff/owners.
-- Class invoice generation totals required fee-item lines when configured, then applies per-student discounts, scholarships and waivers.
