-- Production feature expansion applied via Supabase MCP on 2026-09-25.
-- Keep repository migrations aligned with production.
create table if not exists public.datasub_favourites(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,offering_id uuid not null references public.datasub_catalog_offerings(id) on delete cascade,label text,created_at timestamptz not null default now(),unique(user_id,offering_id));
create table if not exists public.datasub_scheduled_purchases(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,offering_id uuid not null references public.datasub_catalog_offerings(id),recipient text not null,amount numeric,frequency text not null default 'once',next_run_at timestamptz not null,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.datasub_spending_limits(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,daily_limit numeric,monthly_limit numeric,updated_at timestamptz not null default now(),unique(user_id));
create table if not exists public.datasub_disputes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,transaction_id uuid references public.datasub_transactions(id),category text not null,details text not null,status text not null default 'open',resolution text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.datasub_api_webhooks(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,url text not null,events text[] not null default array['transaction.updated'],secret_hash text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.datasub_bulk_jobs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,service_type text not null,total_items int not null default 0,processed_items int not null default 0,failed_items int not null default 0,status text not null default 'draft',created_at timestamptz not null default now());
create table if not exists public.datasub_sms_campaigns(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,message text not null,recipient_count int not null default 0,status text not null default 'draft',scheduled_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.datasub_referrals(id uuid primary key default gen_random_uuid(),referrer_user_id uuid not null references auth.users(id) on delete cascade,referred_user_id uuid references auth.users(id) on delete set null,code text not null unique,status text not null default 'pending',commission numeric not null default 0,created_at timestamptz not null default now());
-- SchoolPro dedicated feature tables.
create table if not exists public.schoolpro_admissions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,applicant_name text not null,guardian_name text,guardian_contact text,class_applied text,status text not null default 'pending',notes text,created_at timestamptz not null default now());
create table if not exists public.schoolpro_cbt_tests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,title text not null,subject_id uuid references public.schoolpro_subjects(id),class_id uuid references public.schoolpro_classes(id),duration_minutes int not null default 30,total_marks numeric not null default 100,status text not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.schoolpro_library_books(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,title text not null,author text,isbn text,copies int not null default 1,available_copies int not null default 1,created_at timestamptz not null default now());
create table if not exists public.schoolpro_transport_routes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,name text not null,vehicle text,driver_name text,driver_phone text,fee numeric not null default 0,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.schoolpro_hostel_rooms(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,hostel_name text not null,room text not null,capacity int not null default 1,occupied int not null default 0,fee numeric not null default 0,created_at timestamptz not null default now());
create table if not exists public.schoolpro_inventory_assets(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,name text not null,category text,quantity int not null default 1,condition text not null default 'good',location text,created_at timestamptz not null default now());
create table if not exists public.schoolpro_calendar_events(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,title text not null,event_date date not null,event_type text,details text,created_at timestamptz not null default now());
create table if not exists public.schoolpro_lesson_notes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,subject_id uuid references public.schoolpro_subjects(id),class_id uuid references public.schoolpro_classes(id),title text not null,content text,status text not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.schoolpro_result_approvals(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,result_id uuid not null references public.schoolpro_results(id) on delete cascade,status text not null default 'pending',reviewed_by uuid references auth.users(id),reviewed_at timestamptz,notes text,unique(result_id));
create table if not exists public.schoolpro_promotions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schoolpro_schools(id) on delete cascade,student_id uuid not null references public.schoolpro_students(id) on delete cascade,from_class text,to_class text,session text not null,status text not null default 'promoted',created_at timestamptz not null default now());
